/**
 * @file
 * @brief Additional MbedTLS user config
 * @copyright 2024 Embeint Holdings Pty Ltd
 * @author Jordan Yates <jordan@embeint.com>
 *
 * SPDX-License-Identifier: FSL-1.1-ALv2
 */

#ifndef INFUSE_SDK_INCLUDE_INFUSE_CRYPTO_TF_PSA_CRYPTO_INFUSE_USER_CONFIG_H_
#define INFUSE_SDK_INCLUDE_INFUSE_CRYPTO_TF_PSA_CRYPTO_INFUSE_USER_CONFIG_H_

#ifdef CONFIG_TF_PSA_CRYPTO_OBERON_ACCELERATOR

#define MBEDTLS_PSA_ACCEL_ALG_CHACHA20_POLY1305

#ifdef CONFIG_TF_PSA_CRYPTO_OBERON_ACCELERATOR_SHA
#define MBEDTLS_PSA_ACCEL_ALG_SHA_1
#define MBEDTLS_PSA_ACCEL_ALG_SHA_224
#define MBEDTLS_PSA_ACCEL_ALG_SHA_256
#define MBEDTLS_PSA_ACCEL_ALG_SHA_384
#define MBEDTLS_PSA_ACCEL_ALG_SHA_512
#endif /* CONFIG_TF_PSA_CRYPTO_OBERON_ACCELERATOR_SHA */

#endif /* CONFIG_TF_PSA_CRYPTO_OBERON_ACCELERATOR */

#endif /* INFUSE_SDK_INCLUDE_INFUSE_CRYPTO_TF_PSA_CRYPTO_INFUSE_USER_CONFIG_H_ */
