/**
 * @file
 * @brief Autogenerated KV store definitions
 * @copyright 2024 Embeint Inc
 * @author scripts/west_commands/cloudgen.py
 *
 * SPDX-License-Identifier: LicenseRef-Embeint
 */

#include <zephyr/toolchain.h>

#include <infuse/fs/kv_types.h>

#include "kv_internal.h"

static struct key_value_slot_definition kv_slots[] = {
#ifdef CONFIG_KV_STORE_KEY_REBOOTS
	{
		.key = KV_KEY_REBOOTS,
		.range = 1,
		.flags = 0,
	},
#endif /* CONFIG_KV_STORE_KEY_REBOOTS */
#ifdef CONFIG_KV_STORE_KEY_BLUETOOTH_ADDR
	{
		.key = KV_KEY_BLUETOOTH_ADDR,
		.range = 1,
		.flags = KV_FLAGS_REFLECT | KV_FLAGS_READ_ONLY,
	},
#endif /* CONFIG_KV_STORE_KEY_BLUETOOTH_ADDR */
#ifdef CONFIG_KV_STORE_KEY_EXFAT_DISK_INFO
	{
		.key = KV_KEY_EXFAT_DISK_INFO,
		.range = 1,
		.flags = KV_FLAGS_REFLECT | KV_FLAGS_READ_ONLY,
	},
#endif /* CONFIG_KV_STORE_KEY_EXFAT_DISK_INFO */
#ifdef CONFIG_KV_STORE_KEY_BLUETOOTH_CTLR_VERSION
	{
		.key = KV_KEY_BLUETOOTH_CTLR_VERSION,
		.range = 1,
		.flags = KV_FLAGS_REFLECT,
	},
#endif /* CONFIG_KV_STORE_KEY_BLUETOOTH_CTLR_VERSION */
#ifdef CONFIG_KV_STORE_KEY_FIXED_LOCATION
	{
		.key = KV_KEY_FIXED_LOCATION,
		.range = 1,
		.flags = KV_FLAGS_REFLECT,
	},
#endif /* CONFIG_KV_STORE_KEY_FIXED_LOCATION */
#ifdef CONFIG_KV_STORE_KEY_WIFI_SSID
	{
		.key = KV_KEY_WIFI_SSID,
		.range = 1,
		.flags = KV_FLAGS_REFLECT,
	},
#endif /* CONFIG_KV_STORE_KEY_WIFI_SSID */
#ifdef CONFIG_KV_STORE_KEY_WIFI_PSK
	{
		.key = KV_KEY_WIFI_PSK,
		.range = 1,
		.flags = KV_FLAGS_REFLECT | KV_FLAGS_WRITE_ONLY,
	},
#endif /* CONFIG_KV_STORE_KEY_WIFI_PSK */
#ifdef CONFIG_KV_STORE_KEY_NTP_SERVER_URL
	{
		.key = KV_KEY_NTP_SERVER_URL,
		.range = 1,
		.flags = KV_FLAGS_REFLECT,
	},
#endif /* CONFIG_KV_STORE_KEY_NTP_SERVER_URL */
#ifdef CONFIG_KV_STORE_KEY_EPACKET_UDP_URL
	{
		.key = KV_KEY_EPACKET_UDP_URL,
		.range = 1,
		.flags = KV_FLAGS_REFLECT,
	},
#endif /* CONFIG_KV_STORE_KEY_EPACKET_UDP_URL */
#ifdef CONFIG_KV_STORE_KEY_EPACKET_UDP_PORT
	{
		.key = KV_KEY_EPACKET_UDP_PORT,
		.range = 1,
		.flags = KV_FLAGS_REFLECT,
	},
#endif /* CONFIG_KV_STORE_KEY_EPACKET_UDP_PORT */
#ifdef CONFIG_KV_STORE_KEY_LTE_MODEM_MODEL
	{
		.key = KV_KEY_LTE_MODEM_MODEL,
		.range = 1,
		.flags = KV_FLAGS_REFLECT | KV_FLAGS_READ_ONLY,
	},
#endif /* CONFIG_KV_STORE_KEY_LTE_MODEM_MODEL */
#ifdef CONFIG_KV_STORE_KEY_LTE_MODEM_FIRMWARE_REVISION
	{
		.key = KV_KEY_LTE_MODEM_FIRMWARE_REVISION,
		.range = 1,
		.flags = KV_FLAGS_REFLECT | KV_FLAGS_READ_ONLY,
	},
#endif /* CONFIG_KV_STORE_KEY_LTE_MODEM_FIRMWARE_REVISION */
#ifdef CONFIG_KV_STORE_KEY_LTE_MODEM_ESN
	{
		.key = KV_KEY_LTE_MODEM_ESN,
		.range = 1,
		.flags = KV_FLAGS_REFLECT | KV_FLAGS_READ_ONLY,
	},
#endif /* CONFIG_KV_STORE_KEY_LTE_MODEM_ESN */
#ifdef CONFIG_KV_STORE_KEY_LTE_MODEM_IMEI
	{
		.key = KV_KEY_LTE_MODEM_IMEI,
		.range = 1,
		.flags = KV_FLAGS_REFLECT | KV_FLAGS_READ_ONLY,
	},
#endif /* CONFIG_KV_STORE_KEY_LTE_MODEM_IMEI */
#ifdef CONFIG_KV_STORE_KEY_LTE_SIM_UICC
	{
		.key = KV_KEY_LTE_SIM_UICC,
		.range = 1,
		.flags = KV_FLAGS_REFLECT | KV_FLAGS_READ_ONLY,
	},
#endif /* CONFIG_KV_STORE_KEY_LTE_SIM_UICC */
#ifdef CONFIG_KV_STORE_KEY_LTE_PDP_CONFIG
	{
		.key = KV_KEY_LTE_PDP_CONFIG,
		.range = 1,
		.flags = KV_FLAGS_REFLECT,
	},
#endif /* CONFIG_KV_STORE_KEY_LTE_PDP_CONFIG */
#ifdef CONFIG_KV_STORE_KEY_LTE_NETWORKING_MODES
	{
		.key = KV_KEY_LTE_NETWORKING_MODES,
		.range = 1,
		.flags = KV_FLAGS_REFLECT,
	},
#endif /* CONFIG_KV_STORE_KEY_LTE_NETWORKING_MODES */
#ifdef CONFIG_KV_STORE_KEY_BLUETOOTH_PEER
	{
		.key = KV_KEY_BLUETOOTH_PEER,
		.range = 1,
		.flags = KV_FLAGS_REFLECT,
	},
#endif /* CONFIG_KV_STORE_KEY_BLUETOOTH_PEER */
#ifdef CONFIG_KV_STORE_KEY_GRAVITY_REFERENCE
	{
		.key = KV_KEY_GRAVITY_REFERENCE,
		.range = 1,
		.flags = KV_FLAGS_REFLECT,
	},
#endif /* CONFIG_KV_STORE_KEY_GRAVITY_REFERENCE */
#ifdef CONFIG_KV_STORE_KEY_GEOFENCE
	{
		.key = KV_KEY_GEOFENCE,
		.range = CONFIG_KV_STORE_KEY_GEOFENCE_RANGE,
		.flags = KV_FLAGS_REFLECT,
	},
#endif /* CONFIG_KV_STORE_KEY_GEOFENCE */
#ifdef CONFIG_KV_STORE_KEY_TASK_SCHEDULES_DEFAULT_ID
	{
		.key = KV_KEY_TASK_SCHEDULES_DEFAULT_ID,
		.range = 1,
		.flags = KV_FLAGS_REFLECT,
	},
#endif /* CONFIG_KV_STORE_KEY_TASK_SCHEDULES_DEFAULT_ID */
#ifdef CONFIG_KV_STORE_KEY_TASK_SCHEDULES
	{
		.key = KV_KEY_TASK_SCHEDULES,
		.range = CONFIG_KV_STORE_KEY_TASK_SCHEDULES_RANGE,
		.flags = KV_FLAGS_REFLECT,
	},
#endif /* CONFIG_KV_STORE_KEY_TASK_SCHEDULES */
#ifdef CONFIG_KV_STORE_KEY_SECURE_STORAGE_RESERVED
	{
		.key = KV_KEY_SECURE_STORAGE_RESERVED,
		.range = CONFIG_KV_STORE_KEY_SECURE_STORAGE_RESERVED_RANGE,
		.flags = 0,
	},
#endif /* CONFIG_KV_STORE_KEY_SECURE_STORAGE_RESERVED */
#ifdef CONFIG_KV_STORE_USER_KEYS
#define KV_STORE_USER_KEYS_ARRAY_DEFINE
#include "infuse_kv_user_keys.c"
#undef KV_STORE_USER_KEYS_ARRAY_DEFINE
#endif
};

/* Detect changes in struct size as this array exists in every application */
BUILD_ASSERT(sizeof(struct key_value_slot_definition) == 4);

struct key_value_slot_definition *kv_internal_slot_definitions(size_t *num)
{
	*num = ARRAY_SIZE(kv_slots);
	return kv_slots;
}
