/**
 * @file
 * @brief Autogenerated KV store definitions
 * @copyright 2024 Embeint Inc
 * @author scripts/west_commands/cloudgen.py
 *
 * SPDX-License-Identifier: LicenseRef-Embeint
 */

#include <zephyr/toolchain.h>

#include "kv_internal.h"

static struct key_value_slot_definition kv_slots[] = {
#ifdef CONFIG_KV_STORE_KEY_REBOOTS
	{
		.key = 0,
		.range = 1,
		.flags = 0,
	},
#endif /* CONFIG_KV_STORE_KEY_REBOOTS */
#ifdef CONFIG_KV_STORE_KEY_BLUETOOTH_ADDR
	{
		.key = 1,
		.range = 1,
		.flags = KV_FLAGS_REFLECT,
	},
#endif /* CONFIG_KV_STORE_KEY_BLUETOOTH_ADDR */
#ifdef CONFIG_KV_STORE_KEY_EXFAT_DISK_INFO
	{
		.key = 2,
		.range = 1,
		.flags = KV_FLAGS_REFLECT | KV_FLAGS_READ_ONLY,
	},
#endif /* CONFIG_KV_STORE_KEY_EXFAT_DISK_INFO */
#ifdef CONFIG_KV_STORE_KEY_BLUETOOTH_CTLR_VERSION
	{
		.key = 3,
		.range = 1,
		.flags = KV_FLAGS_REFLECT,
	},
#endif /* CONFIG_KV_STORE_KEY_BLUETOOTH_CTLR_VERSION */
#ifdef CONFIG_KV_STORE_KEY_FIXED_LOCATION
	{
		.key = 10,
		.range = 1,
		.flags = KV_FLAGS_REFLECT,
	},
#endif /* CONFIG_KV_STORE_KEY_FIXED_LOCATION */
#ifdef CONFIG_KV_STORE_KEY_WIFI_SSID
	{
		.key = 20,
		.range = 1,
		.flags = KV_FLAGS_REFLECT,
	},
#endif /* CONFIG_KV_STORE_KEY_WIFI_SSID */
#ifdef CONFIG_KV_STORE_KEY_WIFI_PSK
	{
		.key = 21,
		.range = 1,
		.flags = KV_FLAGS_REFLECT | KV_FLAGS_WRITE_ONLY,
	},
#endif /* CONFIG_KV_STORE_KEY_WIFI_PSK */
#ifdef CONFIG_KV_STORE_KEY_NTP_SERVER_URL
	{
		.key = 30,
		.range = 1,
		.flags = KV_FLAGS_REFLECT,
	},
#endif /* CONFIG_KV_STORE_KEY_NTP_SERVER_URL */
#ifdef CONFIG_KV_STORE_KEY_EPACKET_UDP_URL
	{
		.key = 31,
		.range = 1,
		.flags = KV_FLAGS_REFLECT,
	},
#endif /* CONFIG_KV_STORE_KEY_EPACKET_UDP_URL */
#ifdef CONFIG_KV_STORE_KEY_EPACKET_UDP_PORT
	{
		.key = 32,
		.range = 1,
		.flags = KV_FLAGS_REFLECT,
	},
#endif /* CONFIG_KV_STORE_KEY_EPACKET_UDP_PORT */
#ifdef CONFIG_KV_STORE_KEY_LTE_MODEM_MODEL
	{
		.key = 40,
		.range = 1,
		.flags = KV_FLAGS_REFLECT | KV_FLAGS_READ_ONLY,
	},
#endif /* CONFIG_KV_STORE_KEY_LTE_MODEM_MODEL */
#ifdef CONFIG_KV_STORE_KEY_LTE_MODEM_FIRMWARE_REVISION
	{
		.key = 41,
		.range = 1,
		.flags = KV_FLAGS_REFLECT | KV_FLAGS_READ_ONLY,
	},
#endif /* CONFIG_KV_STORE_KEY_LTE_MODEM_FIRMWARE_REVISION */
#ifdef CONFIG_KV_STORE_KEY_LTE_MODEM_ESN
	{
		.key = 42,
		.range = 1,
		.flags = KV_FLAGS_REFLECT | KV_FLAGS_READ_ONLY,
	},
#endif /* CONFIG_KV_STORE_KEY_LTE_MODEM_ESN */
#ifdef CONFIG_KV_STORE_KEY_LTE_MODEM_IMEI
	{
		.key = 43,
		.range = 1,
		.flags = KV_FLAGS_REFLECT | KV_FLAGS_READ_ONLY,
	},
#endif /* CONFIG_KV_STORE_KEY_LTE_MODEM_IMEI */
#ifdef CONFIG_KV_STORE_KEY_LTE_SIM_UICC
	{
		.key = 44,
		.range = 1,
		.flags = KV_FLAGS_REFLECT | KV_FLAGS_READ_ONLY,
	},
#endif /* CONFIG_KV_STORE_KEY_LTE_SIM_UICC */
#ifdef CONFIG_KV_STORE_KEY_GEOFENCE
	{
		.key = 100,
		.range = CONFIG_KV_STORE_KEY_GEOFENCE_RANGE,
		.flags = KV_FLAGS_REFLECT,
	},
#endif /* CONFIG_KV_STORE_KEY_GEOFENCE */
#ifdef CONFIG_KV_STORE_KEY_SECURE_STORAGE_RESERVED
	{
		.key = 30000,
		.range = CONFIG_KV_STORE_KEY_SECURE_STORAGE_RESERVED_RANGE,
		.flags = 0,
	},
#endif /* CONFIG_KV_STORE_KEY_SECURE_STORAGE_RESERVED */
};

/* Detect changes in struct size as this array exists in every application */
BUILD_ASSERT(sizeof(struct key_value_slot_definition) == 4);

struct key_value_slot_definition *kv_internal_slot_definitions(size_t *num)
{
	*num = ARRAY_SIZE(kv_slots);
	return kv_slots;
}
