/**
 * @file
 * @brief Autogenerated KV store definitions
 * @copyright 2024 Embeint Pty Ltd
 * @author scripts/west_commands/cloudgen.py
 *
 * SPDX-License-Identifier: LicenseRef-Embeint
 */

#include <zephyr/toolchain.h>

#include "kv_internal.h"

static struct key_value_slot_definition kv_slots[] = {
#ifdef CONFIG_KV_STORE_REBOOTS
	{
		.key = 0,
		.range = 1,
		.flags = 0,
	},
#endif /* CONFIG_KV_STORE_REBOOTS */
#ifdef CONFIG_KV_STORE_FIXED_LOCATION
	{
		.key = 10,
		.range = 1,
		.flags = KV_FLAGS_REFLECT,
	},
#endif /* CONFIG_KV_STORE_FIXED_LOCATION */
#ifdef CONFIG_KV_STORE_WIFI_SSID
	{
		.key = 20,
		.range = 1,
		.flags = KV_FLAGS_REFLECT,
	},
#endif /* CONFIG_KV_STORE_WIFI_SSID */
#ifdef CONFIG_KV_STORE_WIFI_PSK
	{
		.key = 21,
		.range = 1,
		.flags = KV_FLAGS_REFLECT | KV_FLAGS_WRITE_ONLY,
	},
#endif /* CONFIG_KV_STORE_WIFI_PSK */
#ifdef CONFIG_KV_STORE_GEOFENCE
	{
		.key = 100,
		.range = CONFIG_KV_STORE_GEOFENCE_RANGE,
		.flags = KV_FLAGS_REFLECT,
	},
#endif /* CONFIG_KV_STORE_GEOFENCE */
};

/* Detect changes in struct size as this array exists in every application */
BUILD_ASSERT(sizeof(struct key_value_slot_definition) == 4);

struct key_value_slot_definition *kv_internal_slot_definitions(size_t *num)
{
	*num = ARRAY_SIZE(kv_slots);
	return kv_slots;
}
