/**
 * @file
 * @brief Autogenerated RPC definitions
 * @copyright 2024 Embeint Inc
 * @author scripts/west_commands/cloudgen.py
 *
 * SPDX-License-Identifier: LicenseRef-Embeint
 */

#ifndef INFUSE_SDK_INCLUDE_INFUSE_RPC_TYPES_H_
#define INFUSE_SDK_INCLUDE_INFUSE_RPC_TYPES_H_

#include <stdint.h>

#include <zephyr/toolchain.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief RPC packet headers
 * @defgroup rpc_packet_headers RPC packet headers
 * @{
 */

/**
 * @brief Header for @ref INFUSE_RPC_CMD packet
 */
struct infuse_rpc_req_header {
	/* Unique request ID */
	uint32_t request_id;
	/* Command to run */
	uint16_t command_id;
} __packed;

/**
 * @brief Secondary header for RPCs expecting @ref INFUSE_RPC_DATA
 */
struct infuse_rpc_req_data_header {
	/* Amount of data expected to be transferred */
	uint32_t size;
	/* Send an @ref INFUSE_RPC_DATA_ACK response every N packets received */
	uint8_t rx_ack_period;
} __packed;

/**
 * @brief @ref INFUSE_RPC_DATA payload
 */
struct infuse_rpc_data {
	/* Request ID matching original @ref infuse_rpc_req_header */
	uint32_t request_id;
	/* Byte offset of data in this payload */
	uint32_t offset;
	/* Data payload */
	uint8_t payload[];
} __packed;

/**
 * @brief @ref INFUSE_RPC_DATA_ACK packet
 */
struct infuse_rpc_data_ack {
	/* Request ID matching original @ref infuse_rpc_req_header */
	uint32_t request_id;
	/* Byte offsets received */
	uint32_t offsets[];
} __packed;

/**
 * @brief Header for @ref INFUSE_RPC_RSP packet
 */
struct infuse_rpc_rsp_header {
	/* Request ID matching original @ref infuse_rpc_req_header */
	uint32_t request_id;
	/* Command that was run */
	uint16_t command_id;
	/* Result of the RPC */
	int16_t return_code;
} __packed;

/**
 * @}
 */

/* clang-format off */

/**
 * @brief Common RPC struct fields
 * @defgroup rpc_struct_definitions Common RPC struct fields
 * @{
 */

/* MCUboot semantic versioning struct */
struct rpc_struct_mcuboot_img_sem_ver {
	uint8_t major;
	uint8_t minor;
	uint16_t revision;
	uint32_t build_num;
} __packed;

/* KV store data value */
struct rpc_struct_kv_store_value {
	uint16_t id;
	int16_t len;
	uint8_t data[];
} __packed;

/* KV store data CRC */
struct rpc_struct_kv_store_crc {
	uint16_t id;
	int32_t crc;
} __packed;

/* IPv4 address */
struct rpc_struct_ipv4_address {
	uint8_t addr[4];
} __packed;

/* IPv6 address */
struct rpc_struct_ipv6_address {
	uint8_t addr[16];
} __packed;

/* Common network state */
struct rpc_struct_network_state {
	/* Operational state */
	uint8_t state;
	/* Interface flags */
	uint32_t if_flags;
	/* L2 flags */
	uint16_t l2_flags;
	/* Maximum transmission unit */
	uint16_t mtu;
	/* Self IPv4 address */
	struct rpc_struct_ipv4_address ipv4;
	/* Self IPv6 address */
	struct rpc_struct_ipv6_address ipv6;
} __packed;

/* WiFi interface status */
struct rpc_struct_wifi_state {
	/* Operational state */
	uint8_t state;
	/* Service Set Identifier (Network Name) */
	char ssid[32];
	/* Basic Service Set Identifier (MAC address) */
	char bssid[6];
	/* Frequency band */
	uint8_t band;
	/* Channel index */
	uint8_t channel;
	/* https://w1.fi/wpa_supplicant/devel/defs_8h.html#a4aeb27c1e4abd046df3064ea9756f0bc */
	uint8_t iface_mode;
	/* WiFi link operating mode (https://en.wikipedia.org/wiki/Wi-Fi#Versions_and_generations) */
	uint8_t link_mode;
	/* IEEE 802.11 security type */
	uint8_t security;
	/* Received signal strength (dBm) */
	int8_t rssi;
	/* Beacon interval (ms) */
	uint16_t beacon_interval;
	/* Target Wake Time capable? */
	uint8_t twt_capable;
} __packed;

/* LTE interface status */
struct rpc_struct_lte_state {
	/* Network registration state */
	uint8_t registration_state;
	/* 0 = None, 7 = LTE-M, 9 = NB-IoT */
	uint8_t access_technology;
	/* Mobile Country Code */
	uint16_t mcc;
	/* Mobile Network Code */
	uint16_t mnc;
	/* E-UTRAN cell ID */
	uint32_t cell_id;
	/* Tracking area code */
	uint32_t tac;
	/* Tracking area update period */
	uint32_t tau;
	/* Tracking area code (3GPP TS 36.101) */
	uint16_t earfcn;
	/* LTE Band (3GPP 36.101) */
	uint8_t band;
	/* Seconds between RRC idle and PSM */
	uint16_t psm_active_time;
	/* Period between eDRX paging windows */
	float edrx_interval;
	/* Duration of eDRX paging window */
	float edrx_paging_window;
	/* Reference signal received power (dBm) */
	int16_t rsrp;
	/* Reference signal received quality (dB) */
	int8_t rsrq;
} __packed;

/* WiFi interface status */
struct rpc_struct_wifi_scan_result {
	/* Frequency band */
	uint8_t band;
	/* Channel index */
	uint8_t channel;
	/* IEEE 802.11 security type */
	uint8_t security;
	/* Received signal strength (dBm) */
	int8_t rssi;
	/* Basic Service Set Identifier (MAC address) */
	char bssid[6];
	/* SSID length */
	uint8_t ssid_len;
	/* Service Set Identifier (Network Name) */
	char ssid[];
} __packed;

/* Actions to take upon receiving a file */
enum rpc_enum_file_action {
	/* Discard received file (Useful for testing) */
	RPC_ENUM_FILE_ACTION_DISCARD = 0,
	/* Complete application image for firmware upgrade */
	RPC_ENUM_FILE_ACTION_APP_IMG = 1,
	/* Complete Bluetooth controller image for firmware upgrade */
	RPC_ENUM_FILE_ACTION_BT_CTLR_IMG = 2,
	/* nRF91 LTE modem firmware upgrade diff */
	RPC_ENUM_FILE_ACTION_NRF91_MODEM_DIFF = 20,
};

/**
 * @}
 */

/**
 * @brief Builtin RPC definitions
 * @defgroup builtin_rpc_definitions Builtin RPC definitions
 * @{
 */

/* Infuse-IoT builtin RPC commands */
enum rpc_builtin_id {
	/* Reboot the device after a delay */
	RPC_ID_REBOOT = 1,
	/* Immediately trigger an exception on the device */
	RPC_ID_FAULT = 2,
	/* Get the current time knowledge of the device */
	RPC_ID_TIME_GET = 3,
	/* Set the current time of the device */
	RPC_ID_TIME_SET = 4,
	/* Write values to the KV store */
	RPC_ID_KV_WRITE = 5,
	/* Read values from the KV store */
	RPC_ID_KV_READ = 6,
	/* Read KV store CRC's */
	RPC_ID_KV_REFLECT_CRCS = 7,
	/* Query current state of zbus channel */
	RPC_ID_ZBUS_CHANNEL_STATE = 8,
	/* Query basic application versions and state */
	RPC_ID_APPLICATION_INFO = 9,
	/* Scan for WiFi networks */
	RPC_ID_WIFI_SCAN = 10,
	/* Get current WiFi interface state */
	RPC_ID_WIFI_STATE = 11,
	/* Run AT command against LTE modem */
	RPC_ID_LTE_AT_CMD = 20,
	/* Get current LTE interface state */
	RPC_ID_LTE_STATE = 21,
	/* Download a file from a COAP server (Infuse-IoT DTLS protected) */
	RPC_ID_COAP_DOWNLOAD = 30,
	/* Write a file to the device */
	RPC_ID_FILE_WRITE_BASIC = 40,
	/* Query current security state and validate identity */
	RPC_ID_SECURITY_STATE = 30000,
	/* Send multiple INFUSE_RPC_DATA packets */
	RPC_ID_DATA_SENDER = 32765,
	/* Receive multiple INFUSE_RPC_DATA packets */
	RPC_ID_DATA_RECEIVER = 32766,
	/* Echo any input data in the response */
	RPC_ID_ECHO = 32767,
	/* End of builtin RPC range */
	RPC_BUILTIN_END = 32768,
};

/* Reboot the device after a delay */
struct rpc_reboot_request {
	struct infuse_rpc_req_header header;
	/* Requested delay (0 == default) */
	uint32_t delay_ms;
} __packed;

struct rpc_reboot_response {
	struct infuse_rpc_rsp_header header;
	/* Duration until reboot */
	uint32_t delay_ms;
} __packed;

/* Immediately trigger an exception on the device */
struct rpc_fault_request {
	struct infuse_rpc_req_header header;
	/* K_ERR_* fault type to trigger */
	uint8_t fault;
	/* Zero that the compiler doesn't know about */
	uint32_t zero;
} __packed;

struct rpc_fault_response {
	struct infuse_rpc_rsp_header header;
} __packed;

/* Get the current time knowledge of the device */
struct rpc_time_get_request {
	struct infuse_rpc_req_header header;
} __packed;

struct rpc_time_get_response {
	struct infuse_rpc_rsp_header header;
	/* Source of the time knowledge */
	uint8_t time_source;
	/* Current epoch time on the device */
	uint64_t epoch_time;
	/* How old the time knowledge is (seconds) */
	uint32_t sync_age;
} __packed;

/* Set the current time of the device */
struct rpc_time_set_request {
	struct infuse_rpc_req_header header;
	/* Current epoch time on the device */
	uint64_t epoch_time;
} __packed;

struct rpc_time_set_response {
	struct infuse_rpc_rsp_header header;
} __packed;

/* Write values to the KV store */
struct rpc_kv_write_request {
	struct infuse_rpc_req_header header;
	/* Number of values in buffer */
	uint8_t num;
	/* Array of KV values */
	struct rpc_struct_kv_store_value values[];
} __packed;

struct rpc_kv_write_response {
	struct infuse_rpc_rsp_header header;
	/* Result of writes */
	int16_t rc[];
} __packed;

/* Read values from the KV store */
struct rpc_kv_read_request {
	struct infuse_rpc_req_header header;
	/* Number of values to read */
	uint8_t num;
	/* Array of KV keys */
	uint16_t keys[];
} __packed;

struct rpc_kv_read_response {
	struct infuse_rpc_rsp_header header;
	/* Array of KV values */
	struct rpc_struct_kv_store_value values[];
} __packed;

/* Read KV store CRC's */
struct rpc_kv_reflect_crcs_request {
	struct infuse_rpc_req_header header;
	/* Number of CRCs to skip in response */
	uint16_t offset;
} __packed;

struct rpc_kv_reflect_crcs_response {
	struct infuse_rpc_rsp_header header;
	/* Number of CRCs in crcs array */
	uint16_t num;
	/* Number of CRCs that did not fit in this response */
	uint16_t remaining;
	/* Array of KV CRCs */
	struct rpc_struct_kv_store_crc crcs[];
} __packed;

/* Query current state of zbus channel */
struct rpc_zbus_channel_state_request {
	struct infuse_rpc_req_header header;
	/* Channel ID to query */
	uint32_t channel_id;
} __packed;

struct rpc_zbus_channel_state_response {
	struct infuse_rpc_rsp_header header;
	/* Epoch time of last data publish */
	uint64_t publish_timestamp;
	/* Number of times data has been published to channel */
	uint32_t publish_count;
	/* Average time between publishing */
	uint32_t publish_period_avg_ms;
	/* Channel data */
	uint8_t data[];
} __packed;

/* Query basic application versions and state */
struct rpc_application_info_request {
	struct infuse_rpc_req_header header;
} __packed;

struct rpc_application_info_response {
	struct infuse_rpc_rsp_header header;
	/* Application ID */
	uint32_t application_id;
	/* Application version number */
	struct rpc_struct_mcuboot_img_sem_ver version;
	/* Current Infuse network ID */
	uint32_t network_id;
	/* Application uptime */
	uint32_t uptime;
	/* Application reboot count */
	uint32_t reboots;
	/* Key-Value store reflect global CRC */
	uint32_t kv_crc;
	/* Data blocks logged to internal flash */
	uint32_t data_blocks_internal;
	/* Data blocks logged to external flash */
	uint32_t data_blocks_external;
} __packed;

/* Scan for WiFi networks */
struct rpc_wifi_scan_request {
	struct infuse_rpc_req_header header;
} __packed;

struct rpc_wifi_scan_response {
	struct infuse_rpc_rsp_header header;
	/* Number of scanned networks */
	uint8_t network_count;
	/* Array of scanned networks */
	struct rpc_struct_wifi_scan_result networks[];
} __packed;

/* Get current WiFi interface state */
struct rpc_wifi_state_request {
	struct infuse_rpc_req_header header;
} __packed;

struct rpc_wifi_state_response {
	struct infuse_rpc_rsp_header header;
	/* Common network state */
	struct rpc_struct_network_state common;
	/* WiFi state */
	struct rpc_struct_wifi_state wifi;
} __packed;

/* Run AT command against LTE modem */
struct rpc_lte_at_cmd_request {
	struct infuse_rpc_req_header header;
	/* AT command string */
	char cmd[];
} __packed;

struct rpc_lte_at_cmd_response {
	struct infuse_rpc_rsp_header header;
	/* AT command response */
	char rsp[];
} __packed;

/* Get current LTE interface state */
struct rpc_lte_state_request {
	struct infuse_rpc_req_header header;
} __packed;

struct rpc_lte_state_response {
	struct infuse_rpc_rsp_header header;
	/* Common network state */
	struct rpc_struct_network_state common;
	/* LTE state */
	struct rpc_struct_lte_state lte;
} __packed;

/* Download a file from a COAP server (Infuse-IoT DTLS protected) */
struct rpc_coap_download_request {
	struct infuse_rpc_req_header header;
	/* COAP server address (e.g. coap.dev.infuse-iot.com) */
	char server_address[48];
	/* COAP server port */
	uint16_t server_port;
	/* COAP block timeout (Default 1000ms) */
	uint16_t block_timeout_ms;
	/* Action to apply to downloaded file */
	uint8_t action;
	/* Expected resource length (UINT32_MAX if unknown) */
	uint32_t resource_len;
	/* Expected resource CRC (UINT32_MAX if unknown) */
	uint32_t resource_crc;
	/* Path to file on COAP server (e.g. files/small_file) */
	char resource[];
} __packed;

struct rpc_coap_download_response {
	struct infuse_rpc_rsp_header header;
	/* Length of resource downloaded */
	uint32_t resource_len;
	/* CRC of resource downloaded */
	uint32_t resource_crc;
} __packed;

/* Write a file to the device */
struct rpc_file_write_basic_request {
	struct infuse_rpc_req_header header;
	struct infuse_rpc_req_data_header data_header;
	/* Action to apply to written file */
	uint8_t action;
} __packed;

struct rpc_file_write_basic_response {
	struct infuse_rpc_rsp_header header;
	/* Number of bytes received */
	uint32_t recv_len;
	/* CRC of bytes received */
	uint32_t recv_crc;
} __packed;

/* Query current security state and validate identity */
struct rpc_security_state_request {
	struct infuse_rpc_req_header header;
	/* Random challenge data */
	uint8_t challenge[16];
} __packed;

struct rpc_security_state_response {
	struct infuse_rpc_rsp_header header;
	/* Cloud public ECC key */
	uint8_t cloud_public_key[32];
	/* Device public ECC key */
	uint8_t device_public_key[32];
	/* Current network ID */
	uint32_t network_id;
	/* Type of the challenge response */
	uint8_t challenge_response_type;
	/* Challenge response data */
	uint8_t challenge_response[];
} __packed;

/* Send multiple INFUSE_RPC_DATA packets */
struct rpc_data_sender_request {
	struct infuse_rpc_req_header header;
	struct infuse_rpc_req_data_header data_header;
} __packed;

struct rpc_data_sender_response {
	struct infuse_rpc_rsp_header header;
} __packed;

/* Receive multiple INFUSE_RPC_DATA packets */
struct rpc_data_receiver_request {
	struct infuse_rpc_req_header header;
	struct infuse_rpc_req_data_header data_header;
} __packed;

struct rpc_data_receiver_response {
	struct infuse_rpc_rsp_header header;
	/* Number of bytes received */
	uint32_t received;
} __packed;

/* Echo any input data in the response */
struct rpc_echo_request {
	struct infuse_rpc_req_header header;
	/* Binary data */
	uint8_t array[];
} __packed;

struct rpc_echo_response {
	struct infuse_rpc_rsp_header header;
	/* Binary data */
	uint8_t array[];
} __packed;

/**
 * @}
 */

/* clang-format on */

#ifdef __cplusplus
}
#endif

#endif /* INFUSE_SDK_INCLUDE_INFUSE_RPC_TYPES_H_ */
