/**
 * @file
 * @brief Autogenerated RPC definitions
 * @copyright 2024 Embeint Pty Ltd
 * @author scripts/west_commands/cloudgen.py
 *
 * SPDX-License-Identifier: LicenseRef-Embeint
 */

#ifndef INFUSE_SDK_INCLUDE_INFUSE_RPC_TYPES_H_
#define INFUSE_SDK_INCLUDE_INFUSE_RPC_TYPES_H_

#include <stdint.h>

#include <zephyr/toolchain.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief RPC packet headers
 * @defgroup rpc_packet_headers RPC packet headers
 * @{
 */

/**
 * @brief Header for @ref INFUSE_RPC_CMD packet
 */
struct infuse_rpc_req_header {
	/* Unique request ID */
	uint32_t request_id;
	/* Command to run */
	uint16_t command_id;
} __packed;

/**
 * @brief Secondary header for RPCs expecting @ref INFUSE_RPC_DATA
 */
struct infuse_rpc_req_data_header {
	/* Amount of data expected to be transferred */
	uint32_t size;
	/* Send an @ref INFUSE_RPC_DATA_ACK response every N packets received */
	uint8_t rx_ack_period;
};

/**
 * @brief @ref INFUSE_RPC_DATA payload
 */
struct infuse_rpc_data {
	/* Request ID matching original @ref infuse_rpc_req_header */
	uint32_t request_id;
	/* Byte offset of data in this payload */
	uint32_t offset;
	/* Data payload */
	uint8_t payload[];
} __packed;

/**
 * @brief @ref INFUSE_RPC_DATA_ACK packet
 */
struct infuse_rpc_data_ack {
	/* Request ID matching original @ref infuse_rpc_req_header */
	uint32_t request_id;
	/* Byte offsets received */
	uint32_t offsets[];
} __packed;

/**
 * @brief Header for @ref INFUSE_RPC_RSP packet
 */
struct infuse_rpc_rsp_header {
	/* Request ID matching original @ref infuse_rpc_req_header */
	uint32_t request_id;
	/* Result of the RPC */
	int16_t return_code;
} __packed;

/**
 * @}
 */

/**
 * @brief Common RPC struct fields
 * @defgroup rpc_struct_definitions Common RPC struct fields
 * @{
 */

/* MCUboot semantic versioning struct */
struct rpc_struct_mcuboot_img_sem_ver {
	uint8_t major;
	uint8_t minor;
	uint16_t revision;
	uint32_t build_num;
} __packed;

/**
 * @}
 */

/**
 * @brief Builtin RPC definitions
 * @defgroup builtin_rpc_definitions Builtin RPC definitions
 * @{
 */

/* Infuse IoT builtin RPC commands */
enum rpc_builtin_id {
	/* Reboot the device after a delay */
	RPC_ID_REBOOT = 1,
	/* Send multiple INFUSE_RPC_DATA packets */
	RPC_ID_DATA_SENDER = 32765,
	/* Receive multiple INFUSE_RPC_DATA packets */
	RPC_ID_DATA_RECEIVER = 32766,
	/* Echo any input data in the response */
	RPC_ID_ECHO = 32767,
	/* End of builtin RPC range */
	RPC_BUILTIN_END = 32768,
};

/* Reboot the device after a delay */
struct rpc_reboot_request {
	struct infuse_rpc_req_header header;
	/* Requested delay (0 == default) */
	uint32_t delay_ms;
} __packed;

struct rpc_reboot_response {
	struct infuse_rpc_rsp_header header;
	/* Duration until reboot */
	uint32_t delay_ms;
} __packed;

/* Send multiple INFUSE_RPC_DATA packets */
struct rpc_data_sender_request {
	struct infuse_rpc_req_header header;
	struct infuse_rpc_req_data_header data_header;
} __packed;

struct rpc_data_sender_response {
	struct infuse_rpc_rsp_header header;
} __packed;

/* Receive multiple INFUSE_RPC_DATA packets */
struct rpc_data_receiver_request {
	struct infuse_rpc_req_header header;
	struct infuse_rpc_req_data_header data_header;
} __packed;

struct rpc_data_receiver_response {
	struct infuse_rpc_rsp_header header;
	/* Number of bytes received */
	uint32_t received;
} __packed;

/* Echo any input data in the response */
struct rpc_echo_request {
	struct infuse_rpc_req_header header;
	/* Binary data */
	uint8_t array[];
} __packed;

struct rpc_echo_response {
	struct infuse_rpc_rsp_header header;
	/* Binary data */
	uint8_t array[];
} __packed;

/**
 * @}
 */

#ifdef __cplusplus
}
#endif

#endif /* INFUSE_SDK_INCLUDE_INFUSE_RPC_TYPES_H_ */
