/**
 * @file
 * @brief Autogenerated RPC command runner
 * @copyright 2024 Embeint Inc
 * @author scripts/west_commands/cloudgen.py
 *
 * SPDX-License-Identifier: LicenseRef-Embeint
 */

#include <stdbool.h>

#include <zephyr/toolchain.h>
#include <zephyr/net/buf.h>
#include <zephyr/logging/log.h>

#include <infuse/epacket/interface.h>
#include <infuse/epacket/packet.h>
#include <infuse/rpc/types.h>

#include "commands/commands.h"

/* Authorised to run command */
#define AUTHORISED(auth, name) (auth >= CONFIG_INFUSE_RPC_COMMAND_##name##_REQUIRED_AUTH)

static bool command_freed;

LOG_MODULE_DECLARE(rpc_server);

void rpc_command_runner_request_unref(struct net_buf *request)
{
	net_buf_unref(request);
	command_freed = true;
}

void rpc_command_runner(struct net_buf *request)
{
	struct epacket_rx_metadata *metadata = net_buf_user_data(request);
	const struct device *interface = metadata->interface;
	struct infuse_rpc_req_header *req_header = (void *)request->data;
	struct infuse_rpc_rsp_header *rsp_header;
	struct net_buf *response = NULL;
	enum epacket_auth auth = metadata->auth;
	uint32_t request_id = req_header->request_id;
	uint16_t command_id = req_header->command_id;
	int16_t rc = -EACCES;

	/* Reset command freed state */
	command_freed = false;

	LOG_DBG("Handling RPC: %d Auth: %d", command_id, auth);

	switch (command_id) {
#ifdef CONFIG_INFUSE_RPC_COMMAND_REBOOT
	case RPC_ID_REBOOT:
		if (AUTHORISED(auth, REBOOT)) { /* GCOVR_EXCL_BR_LINE */
			response = rpc_command_reboot(request);
		}
		break;
#endif /* CONFIG_INFUSE_RPC_COMMAND_REBOOT */
#ifdef CONFIG_INFUSE_RPC_COMMAND_FAULT
	case RPC_ID_FAULT:
		if (AUTHORISED(auth, FAULT)) { /* GCOVR_EXCL_BR_LINE */
			response = rpc_command_fault(request);
		}
		break;
#endif /* CONFIG_INFUSE_RPC_COMMAND_FAULT */
#ifdef CONFIG_INFUSE_RPC_COMMAND_TIME_GET
	case RPC_ID_TIME_GET:
		if (AUTHORISED(auth, TIME_GET)) { /* GCOVR_EXCL_BR_LINE */
			response = rpc_command_time_get(request);
		}
		break;
#endif /* CONFIG_INFUSE_RPC_COMMAND_TIME_GET */
#ifdef CONFIG_INFUSE_RPC_COMMAND_TIME_SET
	case RPC_ID_TIME_SET:
		if (AUTHORISED(auth, TIME_SET)) { /* GCOVR_EXCL_BR_LINE */
			response = rpc_command_time_set(request);
		}
		break;
#endif /* CONFIG_INFUSE_RPC_COMMAND_TIME_SET */
#ifdef CONFIG_INFUSE_RPC_COMMAND_KV_WRITE
	case RPC_ID_KV_WRITE:
		if (AUTHORISED(auth, KV_WRITE)) { /* GCOVR_EXCL_BR_LINE */
			response = rpc_command_kv_write(request);
		}
		break;
#endif /* CONFIG_INFUSE_RPC_COMMAND_KV_WRITE */
#ifdef CONFIG_INFUSE_RPC_COMMAND_KV_READ
	case RPC_ID_KV_READ:
		if (AUTHORISED(auth, KV_READ)) { /* GCOVR_EXCL_BR_LINE */
			response = rpc_command_kv_read(request);
		}
		break;
#endif /* CONFIG_INFUSE_RPC_COMMAND_KV_READ */
#ifdef CONFIG_INFUSE_RPC_COMMAND_KV_REFLECT_CRCS
	case RPC_ID_KV_REFLECT_CRCS:
		if (AUTHORISED(auth, KV_REFLECT_CRCS)) { /* GCOVR_EXCL_BR_LINE */
			response = rpc_command_kv_reflect_crcs(request);
		}
		break;
#endif /* CONFIG_INFUSE_RPC_COMMAND_KV_REFLECT_CRCS */
#ifdef CONFIG_INFUSE_RPC_COMMAND_ZBUS_CHANNEL_STATE
	case RPC_ID_ZBUS_CHANNEL_STATE:
		if (AUTHORISED(auth, ZBUS_CHANNEL_STATE)) { /* GCOVR_EXCL_BR_LINE */
			response = rpc_command_zbus_channel_state(request);
		}
		break;
#endif /* CONFIG_INFUSE_RPC_COMMAND_ZBUS_CHANNEL_STATE */
#ifdef CONFIG_INFUSE_RPC_COMMAND_APPLICATION_INFO
	case RPC_ID_APPLICATION_INFO:
		if (AUTHORISED(auth, APPLICATION_INFO)) { /* GCOVR_EXCL_BR_LINE */
			response = rpc_command_application_info(request);
		}
		break;
#endif /* CONFIG_INFUSE_RPC_COMMAND_APPLICATION_INFO */
#ifdef CONFIG_INFUSE_RPC_COMMAND_WIFI_SCAN
	case RPC_ID_WIFI_SCAN:
		if (AUTHORISED(auth, WIFI_SCAN)) { /* GCOVR_EXCL_BR_LINE */
			response = rpc_command_wifi_scan(request);
		}
		break;
#endif /* CONFIG_INFUSE_RPC_COMMAND_WIFI_SCAN */
#ifdef CONFIG_INFUSE_RPC_COMMAND_WIFI_STATE
	case RPC_ID_WIFI_STATE:
		if (AUTHORISED(auth, WIFI_STATE)) { /* GCOVR_EXCL_BR_LINE */
			response = rpc_command_wifi_state(request);
		}
		break;
#endif /* CONFIG_INFUSE_RPC_COMMAND_WIFI_STATE */
#ifdef CONFIG_INFUSE_RPC_COMMAND_LAST_REBOOT
	case RPC_ID_LAST_REBOOT:
		if (AUTHORISED(auth, LAST_REBOOT)) { /* GCOVR_EXCL_BR_LINE */
			response = rpc_command_last_reboot(request);
		}
		break;
#endif /* CONFIG_INFUSE_RPC_COMMAND_LAST_REBOOT */
#ifdef CONFIG_INFUSE_RPC_COMMAND_DATA_LOGGER_STATE
	case RPC_ID_DATA_LOGGER_STATE:
		if (AUTHORISED(auth, DATA_LOGGER_STATE)) { /* GCOVR_EXCL_BR_LINE */
			response = rpc_command_data_logger_state(request);
		}
		break;
#endif /* CONFIG_INFUSE_RPC_COMMAND_DATA_LOGGER_STATE */
#ifdef CONFIG_INFUSE_RPC_COMMAND_DATA_LOGGER_READ
	case RPC_ID_DATA_LOGGER_READ:
		if (AUTHORISED(auth, DATA_LOGGER_READ)) { /* GCOVR_EXCL_BR_LINE */
			response = rpc_command_data_logger_read(request);
		}
		break;
#endif /* CONFIG_INFUSE_RPC_COMMAND_DATA_LOGGER_READ */
#ifdef CONFIG_INFUSE_RPC_COMMAND_LTE_AT_CMD
	case RPC_ID_LTE_AT_CMD:
		if (AUTHORISED(auth, LTE_AT_CMD)) { /* GCOVR_EXCL_BR_LINE */
			response = rpc_command_lte_at_cmd(request);
		}
		break;
#endif /* CONFIG_INFUSE_RPC_COMMAND_LTE_AT_CMD */
#ifdef CONFIG_INFUSE_RPC_COMMAND_LTE_STATE
	case RPC_ID_LTE_STATE:
		if (AUTHORISED(auth, LTE_STATE)) { /* GCOVR_EXCL_BR_LINE */
			response = rpc_command_lte_state(request);
		}
		break;
#endif /* CONFIG_INFUSE_RPC_COMMAND_LTE_STATE */
#ifdef CONFIG_INFUSE_RPC_COMMAND_COAP_DOWNLOAD
	case RPC_ID_COAP_DOWNLOAD:
		if (AUTHORISED(auth, COAP_DOWNLOAD)) { /* GCOVR_EXCL_BR_LINE */
			response = rpc_command_coap_download(request);
		}
		break;
#endif /* CONFIG_INFUSE_RPC_COMMAND_COAP_DOWNLOAD */
#ifdef CONFIG_INFUSE_RPC_COMMAND_FILE_WRITE_BASIC
	case RPC_ID_FILE_WRITE_BASIC:
		if (AUTHORISED(auth, FILE_WRITE_BASIC)) { /* GCOVR_EXCL_BR_LINE */
			response = rpc_command_file_write_basic(request);
		}
		break;
#endif /* CONFIG_INFUSE_RPC_COMMAND_FILE_WRITE_BASIC */
#ifdef CONFIG_INFUSE_RPC_COMMAND_BT_CONNECT_INFUSE
	case RPC_ID_BT_CONNECT_INFUSE:
		if (AUTHORISED(auth, BT_CONNECT_INFUSE)) { /* GCOVR_EXCL_BR_LINE */
			response = rpc_command_bt_connect_infuse(request);
		}
		break;
#endif /* CONFIG_INFUSE_RPC_COMMAND_BT_CONNECT_INFUSE */
#ifdef CONFIG_INFUSE_RPC_COMMAND_BT_DISCONNECT
	case RPC_ID_BT_DISCONNECT:
		if (AUTHORISED(auth, BT_DISCONNECT)) { /* GCOVR_EXCL_BR_LINE */
			response = rpc_command_bt_disconnect(request);
		}
		break;
#endif /* CONFIG_INFUSE_RPC_COMMAND_BT_DISCONNECT */
#ifdef CONFIG_INFUSE_RPC_COMMAND_SECURITY_STATE
	case RPC_ID_SECURITY_STATE:
		if (AUTHORISED(auth, SECURITY_STATE)) { /* GCOVR_EXCL_BR_LINE */
			response = rpc_command_security_state(request);
		}
		break;
#endif /* CONFIG_INFUSE_RPC_COMMAND_SECURITY_STATE */
#ifdef CONFIG_INFUSE_RPC_COMMAND_DATA_SENDER
	case RPC_ID_DATA_SENDER:
		if (AUTHORISED(auth, DATA_SENDER)) { /* GCOVR_EXCL_BR_LINE */
			response = rpc_command_data_sender(request);
		}
		break;
#endif /* CONFIG_INFUSE_RPC_COMMAND_DATA_SENDER */
#ifdef CONFIG_INFUSE_RPC_COMMAND_DATA_RECEIVER
	case RPC_ID_DATA_RECEIVER:
		if (AUTHORISED(auth, DATA_RECEIVER)) { /* GCOVR_EXCL_BR_LINE */
			response = rpc_command_data_receiver(request);
		}
		break;
#endif /* CONFIG_INFUSE_RPC_COMMAND_DATA_RECEIVER */
#ifdef CONFIG_INFUSE_RPC_COMMAND_ECHO
	case RPC_ID_ECHO:
		if (AUTHORISED(auth, ECHO)) { /* GCOVR_EXCL_BR_LINE */
			response = rpc_command_echo(request);
		}
		break;
#endif /* CONFIG_INFUSE_RPC_COMMAND_ECHO */
	default:
		rc = -ENOTSUP;
	};

	/* Free the request */
	if (!command_freed) {
		net_buf_unref(request);
	}

	if (response == NULL) {
		/* No command run, alloc the response packet */
		response = epacket_alloc_tx_for_interface(interface, K_FOREVER);
		if (net_buf_tailroom(response) == 0) {
			/* Response channel closed */
			net_buf_unref(response);
			return;
		}
		rsp_header = net_buf_add(response, sizeof(*rsp_header));
		rsp_header->return_code = rc;
	} else {
		rsp_header = (void *)response->data;
	}
	rsp_header->request_id = request_id;
	rsp_header->command_id = command_id;

	/* Metadata and core response info */
	epacket_set_tx_metadata(response, auth, 0x00, INFUSE_RPC_RSP, EPACKET_ADDR_ALL);

	/* Push response back over incoming interface */
	epacket_queue(interface, response);
}
