/**
 * @file
 * @copyright 2024 Embeint Pty Ltd
 * @author Jordan Yates <jordan@embeint.com>
 *
 * SPDX-License-Identifier: LicenseRef-Embeint
 */

#include <zephyr/ztest.h>
#include <zephyr/kernel.h>

#include <infuse/time/civil.h>

ZTEST(civil_time, test_time_source_valid)
{
	zassert_false(civil_time_trusted_source(TIME_SOURCE_NONE, false));
	zassert_false(civil_time_trusted_source(TIME_SOURCE_NONE, true));
	zassert_false(civil_time_trusted_source(TIME_SOURCE_INVALID, false));
	zassert_false(civil_time_trusted_source(TIME_SOURCE_INVALID, true));
	zassert_false(civil_time_trusted_source(33, false));
	zassert_false(civil_time_trusted_source(33, true));
	zassert_false(civil_time_trusted_source(TIME_SOURCE_RECOVERED | TIME_SOURCE_NONE, false));
	zassert_false(civil_time_trusted_source(TIME_SOURCE_RECOVERED | TIME_SOURCE_NONE, true));
	zassert_false(civil_time_trusted_source(TIME_SOURCE_RECOVERED | TIME_SOURCE_INVALID, false));
	zassert_false(civil_time_trusted_source(TIME_SOURCE_RECOVERED | TIME_SOURCE_INVALID, true));
	zassert_false(civil_time_trusted_source(TIME_SOURCE_RECOVERED | 33, false));
	zassert_false(civil_time_trusted_source(TIME_SOURCE_RECOVERED | 33, true));

	zassert_true(civil_time_trusted_source(TIME_SOURCE_GNSS, false));
	zassert_true(civil_time_trusted_source(TIME_SOURCE_GNSS, true));
	zassert_true(civil_time_trusted_source(TIME_SOURCE_NTP, false));
	zassert_true(civil_time_trusted_source(TIME_SOURCE_NTP, true));
	zassert_true(civil_time_trusted_source(TIME_SOURCE_RPC, false));
	zassert_true(civil_time_trusted_source(TIME_SOURCE_RPC, true));
	zassert_false(civil_time_trusted_source(TIME_SOURCE_RECOVERED | TIME_SOURCE_GNSS, false));
	zassert_true(civil_time_trusted_source(TIME_SOURCE_RECOVERED | TIME_SOURCE_GNSS, true));
	zassert_false(civil_time_trusted_source(TIME_SOURCE_RECOVERED | TIME_SOURCE_NTP, false));
	zassert_true(civil_time_trusted_source(TIME_SOURCE_RECOVERED | TIME_SOURCE_NTP, true));
	zassert_false(civil_time_trusted_source(TIME_SOURCE_RECOVERED | TIME_SOURCE_RPC, false));
	zassert_true(civil_time_trusted_source(TIME_SOURCE_RECOVERED | TIME_SOURCE_RPC, true));
}

static void validate_unix_conversions(uint64_t gps_time, uint64_t unix_time, uint16_t subseconds)
{
	uint64_t civil_time;

	civil_time = civil_time_from(gps_time, subseconds);
	zassert_equal(unix_time, unix_time_from_civil(civil_time), "");
	zassert_equal(civil_time, civil_time_from_unix(unix_time, subseconds), "");
}

/* Equivalent times are generated by `hifitime_generator.py`.
 * hifitime is a formally verified time library and should be trusted over websites.
 */
ZTEST(civil_time, test_unix_conversions)
{
	/* 2017-01-01T00:00:00 UTC */
	validate_unix_conversions(1167264018, 1483228800, 0);

	/* 2020-01-01T00:00:00 UTC */
	validate_unix_conversions(1261872018, 1577836800, 0);

	/* 2024-07-02T12:43:01 UTC */
	validate_unix_conversions(1403959399, 1719924181, 0);

	/* 2024-07-02T12:43:01 UTC + (1324/65536) */
	validate_unix_conversions(1403959399, 1719924181, 1324);
}

static void validate_internal(uint64_t civil_time)
{
	uint64_t seconds, subseconds;

	seconds = civil_time_seconds(civil_time);
	subseconds = civil_time_subseconds(civil_time);

	zassert_not_equal(civil_time, seconds, "");
	zassert_not_equal(civil_time, subseconds, "");
	zassert_equal(civil_time, civil_time_from(seconds, subseconds), "");
}

ZTEST(civil_time, test_internal_conversions)
{
	/* Validate at a random time across the whole subsecond range */
	for (int i = 0; i < 100000; i++) {
		validate_internal(12345678910 + i);
	}
}

ZTEST(civil_time, test_gps_conversions)
{
	/* Time equivalents generated from https://gnsscalc.com/ */
	zassert_equal(civil_time_from(1393460764, 0), civil_time_from_gps(2304, 1564, 0), "");
	zassert_equal(civil_time_from(1396138875, 0), civil_time_from_gps(2308, 260475, 0), "");
	zassert_equal(civil_time_from(1446122663, 0), civil_time_from_gps(2391, 45863, 0), "");
}

ZTEST(civil_time, test_local_time_conversion)
{
	struct timeutil_sync_instant reference;
	int rc;

	/* Should boot with 01/01/2020 and TIME_SOURCE_UNKNOWN */
	zassert_equal(TIME_SOURCE_NONE, civil_time_get_source(), "");
	zassert_equal(civil_time_from(1261872018, 0), civil_time_from_ticks(0), "");

	/* Set new reference point */
	reference.local = 0;
	reference.ref = 1000;
	rc = civil_time_set_reference(TIME_SOURCE_GNSS, &reference);
	zassert_equal(0, rc, "Set reference instant failed");

	/* Validate different local device times */
	zassert_equal((0 * INFUSE_CIVIL_TIME_TICKS_PER_SEC) + 1000,
		      civil_time_from_ticks(0 * CONFIG_SYS_CLOCK_TICKS_PER_SEC), "");
	zassert_equal((1 * INFUSE_CIVIL_TIME_TICKS_PER_SEC) + 1000,
		      civil_time_from_ticks(1 * CONFIG_SYS_CLOCK_TICKS_PER_SEC), "");
	zassert_equal((2 * INFUSE_CIVIL_TIME_TICKS_PER_SEC) + 1000,
		      civil_time_from_ticks(2 * CONFIG_SYS_CLOCK_TICKS_PER_SEC), "");
}

ZTEST_SUITE(civil_time, NULL, NULL, NULL, NULL, NULL);
