# The west manifest file for the Infuse SDK.
#
# SPDX-License-Identifier: FSL-1.1-ALv2

manifest:
  defaults:
    remote: embeint

  remotes:
    - name: embeint
      url-base: https://github.com/embeint
    - name: memfault
      url-base: https://github.com/memfault

  projects:
    - name: zephyr
      revision: e5e7ce3a5ce0c1a7b0ebf220bb3fb4d170928dc0
      # Limit imported repositories to reduce clone time
      import:
        name-allowlist:
          - cmsis-dsp
          - cmsis_6
          - hal_nordic
          - hal_st
          - hal_stm32
          - hostap
          - libmetal
          - littlefs
          - lora-basics-modem
          - loramac-node
          - fatfs
          - mbedtls
          - mbedtls-3.6 # Required for TF-M build until TF-M jumps to v2.3
          - open-amp
          - segger
          - nrf_wifi
          - tf-psa-crypto
          - tinycrypt
          - trusted-firmware-m
          - picolibc
          - zcbor
    - name: mcuboot
      revision: 88e5b0bd61bc354ce4c8e2d05113e3c5334930df
      path: bootloader/mcuboot
    - name: sdk-nrf
      path: modules/nrfconnect/sdk-nrf
      revision: 88ea8b334803984be1b5d83659d040f772f954e2
      import: true
    - name: memfault-firmware-sdk
      path: modules/lib/memfault
      revision: 1.37.1
      remote: memfault

  self:
    path: infuse-sdk
    west-commands: scripts/west-commands.yml
    import: submanifests
