# The west manifest file for the Infuse SDK.

manifest:
  defaults:
    remote: embeint

  remotes:
    - name: embeint
      url-base: https://github.com/embeint

  projects:
    - name: zephyr
      revision: f51c2f2f6dcd2a8ff99060c2f01b412619641b1d
      # Limit imported repositories to reduce clone time
      import:
        name-allowlist:
          - cmsis
          - cmsis-dsp
          - hal_nordic
          - segger
          - mcuboot
          - mbedtls
          - trusted-firmware-m
    - name: sdk-nrf
      path: modules/nrfconnect/sdk-nrf
      revision: 9ba0f059f57aa50bdd03c1fc2a75c92e7ed4e7e7
      import: true

  self:
    path: infuse-sdk
    west-commands: scripts/west-commands.yml
