# The west manifest file for the Embeint SDK.

manifest:
  defaults:
    remote: embeint

  remotes:
    - name: embeint
      url-base: https://github.com/embeint

  projects:
    - name: zephyr
      revision: 35606714478b0998e3cf16c4a0bd8d86146c4015
      # Limit imported repositories to limit clone time
      import:
        name-allowlist:
          - cmsis
          - cmsis-dsp
          - hal_nordic
          - segger
          - mcuboot
          - mbedtls
          - trusted-firmware-m
    - name: sdk-nrf
      path: modules/nrfconnect/sdk-nrf
      revision: 6f4888392597b9b21d93db3c27d3a2f3cfa11d9c
      import: true

  self:
    path: embeint-sdk
    west-commands: scripts/west-commands.yml
