# The west manifest file for the Infuse SDK.

manifest:
  defaults:
    remote: embeint

  remotes:
    - name: embeint
      url-base: https://github.com/embeint
    - name: memfault
      url-base: https://github.com/memfault

  projects:
    - name: zephyr
      revision: 2449af8fe449dbf76d86c962e4b0d6c9d700565c
      # Limit imported repositories to reduce clone time
      import:
        name-allowlist:
          - cmsis
          - cmsis-dsp
          - hal_nordic
          - hal_stm32
          - hostap
          - libmetal
          - loramac-node
          - fatfs
          - mcuboot
          - mbedtls
          - open-amp
          - segger
          - nrf_wifi
          - tinycrypt
          - trusted-firmware-m
          - picolibc
          - zcbor
    - name: sdk-nrf
      path: modules/nrfconnect/sdk-nrf
      revision: 83be98321a58fcc35ab738315c752e93f107ce56
      import: true
    - name: memfault-firmware-sdk
      path: modules/lib/memfault
      revision: 1.22.0
      remote: memfault

  self:
    path: infuse-sdk
    west-commands: scripts/west-commands.yml
    import: submanifests
