# The west manifest file for the Infuse SDK.

manifest:
  defaults:
    remote: embeint

  remotes:
    - name: embeint
      url-base: https://github.com/embeint
    - name: memfault
      url-base: https://github.com/memfault

  projects:
    - name: zephyr
      revision: 0740a0473aa748df0b431ca21c15181527b4c816
      # Limit imported repositories to reduce clone time
      import:
        name-allowlist:
          - cmsis
          - cmsis-dsp
          - hal_nordic
          - hal_stm32
          - hostap
          - libmetal
          - lora-basics-modem
          - loramac-node
          - fatfs
          - mcuboot
          - mbedtls
          - open-amp
          - segger
          - nrf_wifi
          - tinycrypt
          - trusted-firmware-m
          - picolibc
          - zcbor
    - name: sdk-nrf
      path: modules/nrfconnect/sdk-nrf
      revision: 5a7cd330f9d8550c05a70e0ef8c8e6dcf1896657
      import: true
    - name: memfault-firmware-sdk
      path: modules/lib/memfault
      revision: 1.22.0
      remote: memfault

  self:
    path: infuse-sdk
    west-commands: scripts/west-commands.yml
    import: submanifests
