# The west manifest file for the Infuse SDK.

manifest:
  defaults:
    remote: embeint

  remotes:
    - name: embeint
      url-base: https://github.com/embeint
    - name: memfault
      url-base: https://github.com/memfault

  projects:
    - name: zephyr
      revision: 2fc66148ea4e801c31662b6cec31f4da4271efed
      # Limit imported repositories to reduce clone time
      import:
        name-allowlist:
          - cmsis-dsp
          - cmsis_6
          - hal_nordic
          - hal_st
          - hal_stm32
          - hostap
          - libmetal
          - lora-basics-modem
          - loramac-node
          - fatfs
          - mcuboot
          - mbedtls
          - open-amp
          - segger
          - nrf_wifi
          - tinycrypt
          - trusted-firmware-m
          - picolibc
          - zcbor
    - name: sdk-nrf
      path: modules/nrfconnect/sdk-nrf
      revision: 7c17ceccaf289dd33fe6453f44820b7bcaab5781
      import: true
    - name: memfault-firmware-sdk
      path: modules/lib/memfault
      revision: 1.30.2
      remote: memfault

  self:
    path: infuse-sdk
    west-commands: scripts/west-commands.yml
    import: submanifests
