# The west manifest file for the Infuse SDK.

manifest:
  defaults:
    remote: embeint

  remotes:
    - name: embeint
      url-base: https://github.com/embeint
    - name: memfault
      url-base: https://github.com/memfault

  projects:
    - name: zephyr
      revision: 88c10bf2deb112e4f4fa2ddeee26f26b1acd3c2e
      # Limit imported repositories to reduce clone time
      import:
        name-allowlist:
          - cmsis
          - cmsis-dsp
          - hal_nordic
          - hal_stm32
          - libmetal
          - fatfs
          - mcuboot
          - mbedtls
          - open-amp
          - segger
          - tinycrypt
          - trusted-firmware-m
          - zcbor
    - name: sdk-nrf
      path: modules/nrfconnect/sdk-nrf
      revision: 563aa8f03456aeb1583487b4c1969c8a99b594ec
      import: true
    - name: memfault-firmware-sdk
      path: modules/lib/memfault
      revision: 1.18.0
      remote: memfault

  self:
    path: infuse-sdk
    west-commands: scripts/west-commands.yml
    import: submanifests
