# The west manifest file for the Infuse SDK.

manifest:
  defaults:
    remote: embeint

  remotes:
    - name: embeint
      url-base: https://github.com/embeint
    - name: memfault
      url-base: https://github.com/memfault

  projects:
    - name: zephyr
      revision: f4d521d7a5c6c50f3507b9027fddf4206c5581d2
      # Limit imported repositories to reduce clone time
      import:
        name-allowlist:
          - cmsis
          - cmsis-dsp
          - hal_nordic
          - hal_stm32
          - hostap
          - libmetal
          - lora-basics-modem
          - loramac-node
          - fatfs
          - mcuboot
          - mbedtls
          - open-amp
          - segger
          - nrf_wifi
          - tinycrypt
          - trusted-firmware-m
          - picolibc
          - zcbor
    - name: sdk-nrf
      path: modules/nrfconnect/sdk-nrf
      revision: c8b5f3902259f530679bbb4dd4c1af7f0cfd431f
      import: true
    - name: memfault-firmware-sdk
      path: modules/lib/memfault
      revision: 1.27.0
      remote: memfault

  self:
    path: infuse-sdk
    west-commands: scripts/west-commands.yml
    import: submanifests
