/**
 * @file
 * @brief Autogenerated TDF definitions
 * @copyright 2024 Embeint Pty Ltd
 * @author scripts/west_commands/cloudgen.py
 *
 * SPDX-License-Identifier: LicenseRef-Embeint
 */

#ifndef EMBEINT_SDK_INCLUDE_EIS_TDF_DEFINITIONS_H_
#define EMBEINT_SDK_INCLUDE_EIS_TDF_DEFINITIONS_H_

#include <stdint.h>

#include <zephyr/toolchain.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Common TDF struct fields
 * @defgroup tdf_struct_definitions Common TDF struct fields
 * @{
 */

/* MCUboot semantic versioning struct */
struct tdf_struct_mcuboot_img_sem_ver {
	uint8_t major;
	uint8_t minor;
	uint16_t revision;
	uint32_t build_num;
} __packed;

/* Generic 3-axis sensor reading */
struct tdf_struct_xyz_16bit {
	int16_t x;
	int16_t y;
	int16_t z;
} __packed;

/**
 * @}
 */

/**
 * @brief Builtin TDF Structure Definitions
 * @defgroup builtin_tdf_definitions TDF Structure Definitions
 * @{
 */

/* Common announcement packet */
struct tdf_announce {
	/* Unique application ID */
	uint32_t application;
	/* Running application version */
	tdf_struct_mcuboot_img_sem_ver version;
	/* Uptime in seconds */
	uint32_t uptime;
	/* Reboot counter */
	uint16_t reboots;
} __packed;

/* General battery state */
struct tdf_battery_state {
	/* Battery voltage in millivolts */
	uint32_t voltage_mv;
	/* Charge current in microamps */
	uint16_t charge_ua;
	/* State of charge in percent */
	uint8_t soc;
} __packed;

/* Example array type */
struct tdf_array_type {
	/* I am an array of length 4 */
	uint8_t array[4];
} __packed;

/* EIS builtin TDF definitions */
enum tdf_builtin_id {
	TDF_ANNOUNCE = 0,
	TDF_BATTERY_STATE = 1,
	TDF_ARRAY_TYPE = 2,
	/* End of builtin TDF range */
	TDF_BUILTIN_END = 1024,
};

/* Size of builtin TDF definitions */
enum tdf_builtin_size {
	_TDF_ANNOUNCE_SIZE = sizeof(struct tdf_announce),
	_TDF_BATTERY_STATE_SIZE = sizeof(struct tdf_battery_state),
	_TDF_ARRAY_TYPE_SIZE = sizeof(struct tdf_array_type),
};

/**
 * @}
 */

#ifdef __cplusplus
}
#endif

#endif /* EMBEINT_SDK_INCLUDE_EIS_TDF_DEFINITIONS_H_ */
