# SPDX-License-Identifier: FSL-1.1-ALv2
# Build a corrected copy of the pinned driver without editing imported sources.
function(infuse_airoc_buffer_accounting)
  set(driver_dir ${ZEPHYR_BASE}/drivers/wifi/infineon)
  set(driver_source ${driver_dir}/airoc_wifi.c)
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${driver_source})
  file(READ ${driver_source} driver)
  set(old_release "(void)net_buf_destroy((struct net_buf *)buffer);")
  if(NOT driver MATCHES "net_buf_destroy")
    return()
  endif()
  string(FIND "${driver}" "${old_release}" release_offset)
  if(release_offset EQUAL -1)
    message(FATAL_ERROR "AIROC buffer release changed; recheck pool accounting workaround")
  endif()
  string(REPLACE "${old_release}" "net_buf_unref((struct net_buf *)buffer);" driver "${driver}")
  set(corrected_source ${PROJECT_BINARY_DIR}/airoc_wifi_accounting.c)
  file(WRITE ${corrected_source} "${driver}")
  get_target_property(sources drivers__wifi SOURCES)
  list(FILTER sources EXCLUDE REGEX "(^|/)airoc_wifi\\.c$")
  set_property(TARGET drivers__wifi PROPERTY SOURCES ${sources} ${corrected_source})
  target_include_directories(drivers__wifi PRIVATE ${driver_dir})
endfunction()
cmake_language(DEFER DIRECTORY ${CMAKE_SOURCE_DIR} CALL infuse_airoc_buffer_accounting)
