/**
 * @file
 * @brief Autogenerated TDF diff functions
 * @copyright 2024 Embeint Inc
 * @author scripts/west_commands/cloudgen.py
 *
 * SPDX-License-Identifier: LicenseRef-Embeint
 */

#include <stdint.h>

#include <zephyr/sys/util.h>

#include <infuse/tdf/definitions.h>

bool tdf_diff_encode_announce(const void *current, const void *next, int8_t *out)
{
	const struct tdf_announce *c = current;
	const struct tdf_announce *n = next;
	int32_t diff0 = n->application - c->application;
	int32_t diff1 = n->version.major - c->version.major;
	int32_t diff2 = n->version.minor - c->version.minor;
	int32_t diff3 = n->version.revision - c->version.revision;
	int32_t diff4 = n->version.build_num - c->version.build_num;
	int32_t diff5 = n->kv_crc - c->kv_crc;
	int32_t diff6 = n->blocks - c->blocks;
	int32_t diff7 = n->uptime - c->uptime;
	int32_t diff8 = n->reboots - c->reboots;
	int32_t diff9 = n->flags - c->flags;

	if (!IN_RANGE(diff0, INT8_MIN, INT8_MAX) || !IN_RANGE(diff1, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff2, INT8_MIN, INT8_MAX) || !IN_RANGE(diff3, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff4, INT8_MIN, INT8_MAX) || !IN_RANGE(diff5, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff6, INT8_MIN, INT8_MAX) || !IN_RANGE(diff7, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff8, INT8_MIN, INT8_MAX) || !IN_RANGE(diff9, INT8_MIN, INT8_MAX) || 0) {
		return false;
	}
	if (out != NULL) {
		out[0] = diff0;
		out[1] = diff1;
		out[2] = diff2;
		out[3] = diff3;
		out[4] = diff4;
		out[5] = diff5;
		out[6] = diff6;
		out[7] = diff7;
		out[8] = diff8;
		out[9] = diff9;
	}
	return true;
}

bool tdf_diff_encode_battery_state(const void *current, const void *next, int8_t *out)
{
	const struct tdf_battery_state *c = current;
	const struct tdf_battery_state *n = next;
	int32_t diff0 = n->voltage_mv - c->voltage_mv;
	int32_t diff1 = n->current_ua - c->current_ua;
	int32_t diff2 = n->soc - c->soc;

	if (!IN_RANGE(diff0, INT8_MIN, INT8_MAX) || !IN_RANGE(diff1, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff2, INT8_MIN, INT8_MAX) || 0) {
		return false;
	}
	if (out != NULL) {
		out[0] = diff0;
		out[1] = diff1;
		out[2] = diff2;
	}
	return true;
}

bool tdf_diff_encode_ambient_temp_pres_hum(const void *current, const void *next, int8_t *out)
{
	const struct tdf_ambient_temp_pres_hum *c = current;
	const struct tdf_ambient_temp_pres_hum *n = next;
	int32_t diff0 = n->temperature - c->temperature;
	int32_t diff1 = n->pressure - c->pressure;
	int32_t diff2 = n->humidity - c->humidity;

	if (!IN_RANGE(diff0, INT8_MIN, INT8_MAX) || !IN_RANGE(diff1, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff2, INT8_MIN, INT8_MAX) || 0) {
		return false;
	}
	if (out != NULL) {
		out[0] = diff0;
		out[1] = diff1;
		out[2] = diff2;
	}
	return true;
}

bool tdf_diff_encode_ambient_temperature(const void *current, const void *next, int8_t *out)
{
	const struct tdf_ambient_temperature *c = current;
	const struct tdf_ambient_temperature *n = next;
	int32_t diff0 = n->temperature - c->temperature;

	if (!IN_RANGE(diff0, INT8_MIN, INT8_MAX) || 0) {
		return false;
	}
	if (out != NULL) {
		out[0] = diff0;
	}
	return true;
}

bool tdf_diff_encode_time_sync(const void *current, const void *next, int8_t *out)
{
	const struct tdf_time_sync *c = current;
	const struct tdf_time_sync *n = next;
	int32_t diff0 = n->source - c->source;
	int32_t diff1 = n->shift - c->shift;

	if (!IN_RANGE(diff0, INT8_MIN, INT8_MAX) || !IN_RANGE(diff1, INT8_MIN, INT8_MAX) || 0) {
		return false;
	}
	if (out != NULL) {
		out[0] = diff0;
		out[1] = diff1;
	}
	return true;
}

bool tdf_diff_encode_reboot_info(const void *current, const void *next, int8_t *out)
{
	const struct tdf_reboot_info *c = current;
	const struct tdf_reboot_info *n = next;
	int32_t diff0 = n->reason - c->reason;
	int32_t diff1 = n->hardware_flags - c->hardware_flags;
	int32_t diff2 = n->count - c->count;
	int32_t diff3 = n->uptime - c->uptime;
	int32_t diff4 = n->param_1 - c->param_1;
	int32_t diff5 = n->param_2 - c->param_2;
	int32_t diff6 = n->thread[0] - c->thread[0];
	int32_t diff7 = n->thread[1] - c->thread[1];
	int32_t diff8 = n->thread[2] - c->thread[2];
	int32_t diff9 = n->thread[3] - c->thread[3];
	int32_t diff10 = n->thread[4] - c->thread[4];
	int32_t diff11 = n->thread[5] - c->thread[5];
	int32_t diff12 = n->thread[6] - c->thread[6];
	int32_t diff13 = n->thread[7] - c->thread[7];

	if (!IN_RANGE(diff0, INT8_MIN, INT8_MAX) || !IN_RANGE(diff1, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff2, INT8_MIN, INT8_MAX) || !IN_RANGE(diff3, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff4, INT8_MIN, INT8_MAX) || !IN_RANGE(diff5, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff6, INT8_MIN, INT8_MAX) || !IN_RANGE(diff7, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff8, INT8_MIN, INT8_MAX) || !IN_RANGE(diff9, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff10, INT8_MIN, INT8_MAX) || !IN_RANGE(diff11, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff12, INT8_MIN, INT8_MAX) || !IN_RANGE(diff13, INT8_MIN, INT8_MAX) || 0) {
		return false;
	}
	if (out != NULL) {
		out[0] = diff0;
		out[1] = diff1;
		out[2] = diff2;
		out[3] = diff3;
		out[4] = diff4;
		out[5] = diff5;
		out[6] = diff6;
		out[7] = diff7;
		out[8] = diff8;
		out[9] = diff9;
		out[10] = diff10;
		out[11] = diff11;
		out[12] = diff12;
		out[13] = diff13;
	}
	return true;
}

bool tdf_diff_encode_acc_2g(const void *current, const void *next, int8_t *out)
{
	const struct tdf_acc_2g *c = current;
	const struct tdf_acc_2g *n = next;
	int32_t diff0 = n->sample.x - c->sample.x;
	int32_t diff1 = n->sample.y - c->sample.y;
	int32_t diff2 = n->sample.z - c->sample.z;

	if (!IN_RANGE(diff0, INT8_MIN, INT8_MAX) || !IN_RANGE(diff1, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff2, INT8_MIN, INT8_MAX) || 0) {
		return false;
	}
	if (out != NULL) {
		out[0] = diff0;
		out[1] = diff1;
		out[2] = diff2;
	}
	return true;
}

bool tdf_diff_encode_acc_4g(const void *current, const void *next, int8_t *out)
{
	const struct tdf_acc_4g *c = current;
	const struct tdf_acc_4g *n = next;
	int32_t diff0 = n->sample.x - c->sample.x;
	int32_t diff1 = n->sample.y - c->sample.y;
	int32_t diff2 = n->sample.z - c->sample.z;

	if (!IN_RANGE(diff0, INT8_MIN, INT8_MAX) || !IN_RANGE(diff1, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff2, INT8_MIN, INT8_MAX) || 0) {
		return false;
	}
	if (out != NULL) {
		out[0] = diff0;
		out[1] = diff1;
		out[2] = diff2;
	}
	return true;
}

bool tdf_diff_encode_acc_8g(const void *current, const void *next, int8_t *out)
{
	const struct tdf_acc_8g *c = current;
	const struct tdf_acc_8g *n = next;
	int32_t diff0 = n->sample.x - c->sample.x;
	int32_t diff1 = n->sample.y - c->sample.y;
	int32_t diff2 = n->sample.z - c->sample.z;

	if (!IN_RANGE(diff0, INT8_MIN, INT8_MAX) || !IN_RANGE(diff1, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff2, INT8_MIN, INT8_MAX) || 0) {
		return false;
	}
	if (out != NULL) {
		out[0] = diff0;
		out[1] = diff1;
		out[2] = diff2;
	}
	return true;
}

bool tdf_diff_encode_acc_16g(const void *current, const void *next, int8_t *out)
{
	const struct tdf_acc_16g *c = current;
	const struct tdf_acc_16g *n = next;
	int32_t diff0 = n->sample.x - c->sample.x;
	int32_t diff1 = n->sample.y - c->sample.y;
	int32_t diff2 = n->sample.z - c->sample.z;

	if (!IN_RANGE(diff0, INT8_MIN, INT8_MAX) || !IN_RANGE(diff1, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff2, INT8_MIN, INT8_MAX) || 0) {
		return false;
	}
	if (out != NULL) {
		out[0] = diff0;
		out[1] = diff1;
		out[2] = diff2;
	}
	return true;
}

bool tdf_diff_encode_gyr_125dps(const void *current, const void *next, int8_t *out)
{
	const struct tdf_gyr_125dps *c = current;
	const struct tdf_gyr_125dps *n = next;
	int32_t diff0 = n->sample.x - c->sample.x;
	int32_t diff1 = n->sample.y - c->sample.y;
	int32_t diff2 = n->sample.z - c->sample.z;

	if (!IN_RANGE(diff0, INT8_MIN, INT8_MAX) || !IN_RANGE(diff1, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff2, INT8_MIN, INT8_MAX) || 0) {
		return false;
	}
	if (out != NULL) {
		out[0] = diff0;
		out[1] = diff1;
		out[2] = diff2;
	}
	return true;
}

bool tdf_diff_encode_gyr_250dps(const void *current, const void *next, int8_t *out)
{
	const struct tdf_gyr_250dps *c = current;
	const struct tdf_gyr_250dps *n = next;
	int32_t diff0 = n->sample.x - c->sample.x;
	int32_t diff1 = n->sample.y - c->sample.y;
	int32_t diff2 = n->sample.z - c->sample.z;

	if (!IN_RANGE(diff0, INT8_MIN, INT8_MAX) || !IN_RANGE(diff1, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff2, INT8_MIN, INT8_MAX) || 0) {
		return false;
	}
	if (out != NULL) {
		out[0] = diff0;
		out[1] = diff1;
		out[2] = diff2;
	}
	return true;
}

bool tdf_diff_encode_gyr_500dps(const void *current, const void *next, int8_t *out)
{
	const struct tdf_gyr_500dps *c = current;
	const struct tdf_gyr_500dps *n = next;
	int32_t diff0 = n->sample.x - c->sample.x;
	int32_t diff1 = n->sample.y - c->sample.y;
	int32_t diff2 = n->sample.z - c->sample.z;

	if (!IN_RANGE(diff0, INT8_MIN, INT8_MAX) || !IN_RANGE(diff1, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff2, INT8_MIN, INT8_MAX) || 0) {
		return false;
	}
	if (out != NULL) {
		out[0] = diff0;
		out[1] = diff1;
		out[2] = diff2;
	}
	return true;
}

bool tdf_diff_encode_gyr_1000dps(const void *current, const void *next, int8_t *out)
{
	const struct tdf_gyr_1000dps *c = current;
	const struct tdf_gyr_1000dps *n = next;
	int32_t diff0 = n->sample.x - c->sample.x;
	int32_t diff1 = n->sample.y - c->sample.y;
	int32_t diff2 = n->sample.z - c->sample.z;

	if (!IN_RANGE(diff0, INT8_MIN, INT8_MAX) || !IN_RANGE(diff1, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff2, INT8_MIN, INT8_MAX) || 0) {
		return false;
	}
	if (out != NULL) {
		out[0] = diff0;
		out[1] = diff1;
		out[2] = diff2;
	}
	return true;
}

bool tdf_diff_encode_gyr_2000dps(const void *current, const void *next, int8_t *out)
{
	const struct tdf_gyr_2000dps *c = current;
	const struct tdf_gyr_2000dps *n = next;
	int32_t diff0 = n->sample.x - c->sample.x;
	int32_t diff1 = n->sample.y - c->sample.y;
	int32_t diff2 = n->sample.z - c->sample.z;

	if (!IN_RANGE(diff0, INT8_MIN, INT8_MAX) || !IN_RANGE(diff1, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff2, INT8_MIN, INT8_MAX) || 0) {
		return false;
	}
	if (out != NULL) {
		out[0] = diff0;
		out[1] = diff1;
		out[2] = diff2;
	}
	return true;
}

bool tdf_diff_encode_gcs_wgs84_llha(const void *current, const void *next, int8_t *out)
{
	const struct tdf_gcs_wgs84_llha *c = current;
	const struct tdf_gcs_wgs84_llha *n = next;
	int32_t diff0 = n->location.latitude - c->location.latitude;
	int32_t diff1 = n->location.longitude - c->location.longitude;
	int32_t diff2 = n->location.height - c->location.height;
	int32_t diff3 = n->h_acc - c->h_acc;
	int32_t diff4 = n->v_acc - c->v_acc;

	if (!IN_RANGE(diff0, INT8_MIN, INT8_MAX) || !IN_RANGE(diff1, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff2, INT8_MIN, INT8_MAX) || !IN_RANGE(diff3, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff4, INT8_MIN, INT8_MAX) || 0) {
		return false;
	}
	if (out != NULL) {
		out[0] = diff0;
		out[1] = diff1;
		out[2] = diff2;
		out[3] = diff3;
		out[4] = diff4;
	}
	return true;
}

bool tdf_diff_encode_ubx_nav_pvt(const void *current, const void *next, int8_t *out)
{
	const struct tdf_ubx_nav_pvt *c = current;
	const struct tdf_ubx_nav_pvt *n = next;
	int32_t diff0 = n->itow - c->itow;
	int32_t diff1 = n->year - c->year;
	int32_t diff2 = n->month - c->month;
	int32_t diff3 = n->day - c->day;
	int32_t diff4 = n->hour - c->hour;
	int32_t diff5 = n->min - c->min;
	int32_t diff6 = n->sec - c->sec;
	int32_t diff7 = n->valid - c->valid;
	int32_t diff8 = n->t_acc - c->t_acc;
	int32_t diff9 = n->nano - c->nano;
	int32_t diff10 = n->fix_type - c->fix_type;
	int32_t diff11 = n->flags - c->flags;
	int32_t diff12 = n->flags2 - c->flags2;
	int32_t diff13 = n->num_sv - c->num_sv;
	int32_t diff14 = n->lon - c->lon;
	int32_t diff15 = n->lat - c->lat;
	int32_t diff16 = n->height - c->height;
	int32_t diff17 = n->h_msl - c->h_msl;
	int32_t diff18 = n->h_acc - c->h_acc;
	int32_t diff19 = n->v_acc - c->v_acc;
	int32_t diff20 = n->vel_n - c->vel_n;
	int32_t diff21 = n->vel_e - c->vel_e;
	int32_t diff22 = n->vel_d - c->vel_d;
	int32_t diff23 = n->g_speed - c->g_speed;
	int32_t diff24 = n->head_mot - c->head_mot;
	int32_t diff25 = n->s_acc - c->s_acc;
	int32_t diff26 = n->head_acc - c->head_acc;
	int32_t diff27 = n->p_dop - c->p_dop;
	int32_t diff28 = n->flags3 - c->flags3;
	int32_t diff29 = n->reserved0[0] - c->reserved0[0];
	int32_t diff30 = n->reserved0[1] - c->reserved0[1];
	int32_t diff31 = n->reserved0[2] - c->reserved0[2];
	int32_t diff32 = n->reserved0[3] - c->reserved0[3];
	int32_t diff33 = n->head_veh - c->head_veh;
	int32_t diff34 = n->mag_dec - c->mag_dec;
	int32_t diff35 = n->mag_acc - c->mag_acc;

	if (!IN_RANGE(diff0, INT8_MIN, INT8_MAX) || !IN_RANGE(diff1, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff2, INT8_MIN, INT8_MAX) || !IN_RANGE(diff3, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff4, INT8_MIN, INT8_MAX) || !IN_RANGE(diff5, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff6, INT8_MIN, INT8_MAX) || !IN_RANGE(diff7, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff8, INT8_MIN, INT8_MAX) || !IN_RANGE(diff9, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff10, INT8_MIN, INT8_MAX) || !IN_RANGE(diff11, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff12, INT8_MIN, INT8_MAX) || !IN_RANGE(diff13, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff14, INT8_MIN, INT8_MAX) || !IN_RANGE(diff15, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff16, INT8_MIN, INT8_MAX) || !IN_RANGE(diff17, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff18, INT8_MIN, INT8_MAX) || !IN_RANGE(diff19, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff20, INT8_MIN, INT8_MAX) || !IN_RANGE(diff21, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff22, INT8_MIN, INT8_MAX) || !IN_RANGE(diff23, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff24, INT8_MIN, INT8_MAX) || !IN_RANGE(diff25, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff26, INT8_MIN, INT8_MAX) || !IN_RANGE(diff27, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff28, INT8_MIN, INT8_MAX) || !IN_RANGE(diff29, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff30, INT8_MIN, INT8_MAX) || !IN_RANGE(diff31, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff32, INT8_MIN, INT8_MAX) || !IN_RANGE(diff33, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff34, INT8_MIN, INT8_MAX) || !IN_RANGE(diff35, INT8_MIN, INT8_MAX) || 0) {
		return false;
	}
	if (out != NULL) {
		out[0] = diff0;
		out[1] = diff1;
		out[2] = diff2;
		out[3] = diff3;
		out[4] = diff4;
		out[5] = diff5;
		out[6] = diff6;
		out[7] = diff7;
		out[8] = diff8;
		out[9] = diff9;
		out[10] = diff10;
		out[11] = diff11;
		out[12] = diff12;
		out[13] = diff13;
		out[14] = diff14;
		out[15] = diff15;
		out[16] = diff16;
		out[17] = diff17;
		out[18] = diff18;
		out[19] = diff19;
		out[20] = diff20;
		out[21] = diff21;
		out[22] = diff22;
		out[23] = diff23;
		out[24] = diff24;
		out[25] = diff25;
		out[26] = diff26;
		out[27] = diff27;
		out[28] = diff28;
		out[29] = diff29;
		out[30] = diff30;
		out[31] = diff31;
		out[32] = diff32;
		out[33] = diff33;
		out[34] = diff34;
		out[35] = diff35;
	}
	return true;
}

bool tdf_diff_encode_lte_conn_status(const void *current, const void *next, int8_t *out)
{
	const struct tdf_lte_conn_status *c = current;
	const struct tdf_lte_conn_status *n = next;
	int32_t diff0 = n->cell.mcc - c->cell.mcc;
	int32_t diff1 = n->cell.mnc - c->cell.mnc;
	int32_t diff2 = n->cell.eci - c->cell.eci;
	int32_t diff3 = n->cell.tac - c->cell.tac;
	int32_t diff4 = n->earfcn - c->earfcn;
	int32_t diff5 = n->status - c->status;
	int32_t diff6 = n->tech - c->tech;
	int32_t diff7 = n->rsrp - c->rsrp;
	int32_t diff8 = n->rsrq - c->rsrq;

	if (!IN_RANGE(diff0, INT8_MIN, INT8_MAX) || !IN_RANGE(diff1, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff2, INT8_MIN, INT8_MAX) || !IN_RANGE(diff3, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff4, INT8_MIN, INT8_MAX) || !IN_RANGE(diff5, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff6, INT8_MIN, INT8_MAX) || !IN_RANGE(diff7, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff8, INT8_MIN, INT8_MAX) || 0) {
		return false;
	}
	if (out != NULL) {
		out[0] = diff0;
		out[1] = diff1;
		out[2] = diff2;
		out[3] = diff3;
		out[4] = diff4;
		out[5] = diff5;
		out[6] = diff6;
		out[7] = diff7;
		out[8] = diff8;
	}
	return true;
}

bool tdf_diff_encode_globalstar_pkt(const void *current, const void *next, int8_t *out)
{
	const struct tdf_globalstar_pkt *c = current;
	const struct tdf_globalstar_pkt *n = next;
	int32_t diff0 = n->payload[0] - c->payload[0];
	int32_t diff1 = n->payload[1] - c->payload[1];
	int32_t diff2 = n->payload[2] - c->payload[2];
	int32_t diff3 = n->payload[3] - c->payload[3];
	int32_t diff4 = n->payload[4] - c->payload[4];
	int32_t diff5 = n->payload[5] - c->payload[5];
	int32_t diff6 = n->payload[6] - c->payload[6];
	int32_t diff7 = n->payload[7] - c->payload[7];
	int32_t diff8 = n->payload[8] - c->payload[8];

	if (!IN_RANGE(diff0, INT8_MIN, INT8_MAX) || !IN_RANGE(diff1, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff2, INT8_MIN, INT8_MAX) || !IN_RANGE(diff3, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff4, INT8_MIN, INT8_MAX) || !IN_RANGE(diff5, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff6, INT8_MIN, INT8_MAX) || !IN_RANGE(diff7, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff8, INT8_MIN, INT8_MAX) || 0) {
		return false;
	}
	if (out != NULL) {
		out[0] = diff0;
		out[1] = diff1;
		out[2] = diff2;
		out[3] = diff3;
		out[4] = diff4;
		out[5] = diff5;
		out[6] = diff6;
		out[7] = diff7;
		out[8] = diff8;
	}
	return true;
}

bool tdf_diff_encode_acc_magnitude_std_dev(const void *current, const void *next, int8_t *out)
{
	const struct tdf_acc_magnitude_std_dev *c = current;
	const struct tdf_acc_magnitude_std_dev *n = next;
	int32_t diff0 = n->count - c->count;
	int32_t diff1 = n->std_dev - c->std_dev;

	if (!IN_RANGE(diff0, INT8_MIN, INT8_MAX) || !IN_RANGE(diff1, INT8_MIN, INT8_MAX) || 0) {
		return false;
	}
	if (out != NULL) {
		out[0] = diff0;
		out[1] = diff1;
	}
	return true;
}

bool tdf_diff_encode_activity_metric(const void *current, const void *next, int8_t *out)
{
	const struct tdf_activity_metric *c = current;
	const struct tdf_activity_metric *n = next;
	int32_t diff0 = n->value - c->value;

	if (!IN_RANGE(diff0, INT8_MIN, INT8_MAX) || 0) {
		return false;
	}
	if (out != NULL) {
		out[0] = diff0;
	}
	return true;
}

bool tdf_diff_encode_runtime_error(const void *current, const void *next, int8_t *out)
{
	const struct tdf_runtime_error *c = current;
	const struct tdf_runtime_error *n = next;
	int32_t diff0 = n->error_id - c->error_id;
	int32_t diff1 = n->error_ctx - c->error_ctx;

	if (!IN_RANGE(diff0, INT8_MIN, INT8_MAX) || !IN_RANGE(diff1, INT8_MIN, INT8_MAX) || 0) {
		return false;
	}
	if (out != NULL) {
		out[0] = diff0;
		out[1] = diff1;
	}
	return true;
}

bool tdf_diff_encode_charger_en_control(const void *current, const void *next, int8_t *out)
{
	const struct tdf_charger_en_control *c = current;
	const struct tdf_charger_en_control *n = next;
	int32_t diff0 = n->enabled - c->enabled;

	if (!IN_RANGE(diff0, INT8_MIN, INT8_MAX) || 0) {
		return false;
	}
	if (out != NULL) {
		out[0] = diff0;
	}
	return true;
}

bool tdf_diff_encode_gnss_fix_info(const void *current, const void *next, int8_t *out)
{
	const struct tdf_gnss_fix_info *c = current;
	const struct tdf_gnss_fix_info *n = next;
	int32_t diff0 = n->time_fix - c->time_fix;
	int32_t diff1 = n->location_fix - c->location_fix;
	int32_t diff2 = n->num_sv - c->num_sv;

	if (!IN_RANGE(diff0, INT8_MIN, INT8_MAX) || !IN_RANGE(diff1, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff2, INT8_MIN, INT8_MAX) || 0) {
		return false;
	}
	if (out != NULL) {
		out[0] = diff0;
		out[1] = diff1;
		out[2] = diff2;
	}
	return true;
}

bool tdf_diff_encode_bluetooth_connection(const void *current, const void *next, int8_t *out)
{
	const struct tdf_bluetooth_connection *c = current;
	const struct tdf_bluetooth_connection *n = next;
	int32_t diff0 = n->address.type - c->address.type;
	int32_t diff1 = n->address.val[0] - c->address.val[0];
	int32_t diff2 = n->address.val[1] - c->address.val[1];
	int32_t diff3 = n->address.val[2] - c->address.val[2];
	int32_t diff4 = n->address.val[3] - c->address.val[3];
	int32_t diff5 = n->address.val[4] - c->address.val[4];
	int32_t diff6 = n->address.val[5] - c->address.val[5];
	int32_t diff7 = n->connected - c->connected;

	if (!IN_RANGE(diff0, INT8_MIN, INT8_MAX) || !IN_RANGE(diff1, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff2, INT8_MIN, INT8_MAX) || !IN_RANGE(diff3, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff4, INT8_MIN, INT8_MAX) || !IN_RANGE(diff5, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff6, INT8_MIN, INT8_MAX) || !IN_RANGE(diff7, INT8_MIN, INT8_MAX) || 0) {
		return false;
	}
	if (out != NULL) {
		out[0] = diff0;
		out[1] = diff1;
		out[2] = diff2;
		out[3] = diff3;
		out[4] = diff4;
		out[5] = diff5;
		out[6] = diff6;
		out[7] = diff7;
	}
	return true;
}

bool tdf_diff_encode_bluetooth_rssi(const void *current, const void *next, int8_t *out)
{
	const struct tdf_bluetooth_rssi *c = current;
	const struct tdf_bluetooth_rssi *n = next;
	int32_t diff0 = n->address.type - c->address.type;
	int32_t diff1 = n->address.val[0] - c->address.val[0];
	int32_t diff2 = n->address.val[1] - c->address.val[1];
	int32_t diff3 = n->address.val[2] - c->address.val[2];
	int32_t diff4 = n->address.val[3] - c->address.val[3];
	int32_t diff5 = n->address.val[4] - c->address.val[4];
	int32_t diff6 = n->address.val[5] - c->address.val[5];
	int32_t diff7 = n->rssi - c->rssi;

	if (!IN_RANGE(diff0, INT8_MIN, INT8_MAX) || !IN_RANGE(diff1, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff2, INT8_MIN, INT8_MAX) || !IN_RANGE(diff3, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff4, INT8_MIN, INT8_MAX) || !IN_RANGE(diff5, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff6, INT8_MIN, INT8_MAX) || !IN_RANGE(diff7, INT8_MIN, INT8_MAX) || 0) {
		return false;
	}
	if (out != NULL) {
		out[0] = diff0;
		out[1] = diff1;
		out[2] = diff2;
		out[3] = diff3;
		out[4] = diff4;
		out[5] = diff5;
		out[6] = diff6;
		out[7] = diff7;
	}
	return true;
}

bool tdf_diff_encode_bluetooth_data_throughput(const void *current, const void *next, int8_t *out)
{
	const struct tdf_bluetooth_data_throughput *c = current;
	const struct tdf_bluetooth_data_throughput *n = next;
	int32_t diff0 = n->address.type - c->address.type;
	int32_t diff1 = n->address.val[0] - c->address.val[0];
	int32_t diff2 = n->address.val[1] - c->address.val[1];
	int32_t diff3 = n->address.val[2] - c->address.val[2];
	int32_t diff4 = n->address.val[3] - c->address.val[3];
	int32_t diff5 = n->address.val[4] - c->address.val[4];
	int32_t diff6 = n->address.val[5] - c->address.val[5];
	int32_t diff7 = n->throughput - c->throughput;

	if (!IN_RANGE(diff0, INT8_MIN, INT8_MAX) || !IN_RANGE(diff1, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff2, INT8_MIN, INT8_MAX) || !IN_RANGE(diff3, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff4, INT8_MIN, INT8_MAX) || !IN_RANGE(diff5, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff6, INT8_MIN, INT8_MAX) || !IN_RANGE(diff7, INT8_MIN, INT8_MAX) || 0) {
		return false;
	}
	if (out != NULL) {
		out[0] = diff0;
		out[1] = diff1;
		out[2] = diff2;
		out[3] = diff3;
		out[4] = diff4;
		out[5] = diff5;
		out[6] = diff6;
		out[7] = diff7;
	}
	return true;
}

bool tdf_diff_encode_array_type(const void *current, const void *next, int8_t *out)
{
	const struct tdf_array_type *c = current;
	const struct tdf_array_type *n = next;
	int32_t diff0 = n->array[0] - c->array[0];
	int32_t diff1 = n->array[1] - c->array[1];
	int32_t diff2 = n->array[2] - c->array[2];
	int32_t diff3 = n->array[3] - c->array[3];

	if (!IN_RANGE(diff0, INT8_MIN, INT8_MAX) || !IN_RANGE(diff1, INT8_MIN, INT8_MAX) ||
	    !IN_RANGE(diff2, INT8_MIN, INT8_MAX) || !IN_RANGE(diff3, INT8_MIN, INT8_MAX) || 0) {
		return false;
	}
	if (out != NULL) {
		out[0] = diff0;
		out[1] = diff1;
		out[2] = diff2;
		out[3] = diff3;
	}
	return true;
}
