/**
 * @file
 * @brief Autogenerated RPC command list
 * @copyright 2024 Embeint Inc
 * @author scripts/west_commands/cloudgen.py
 *
 * SPDX-License-Identifier: LicenseRef-Embeint
 */

#ifndef INFUSE_SDK_SUBSYS_RPC_COMMANDS_COMMANDS_H_
#define INFUSE_SDK_SUBSYS_RPC_COMMANDS_COMMANDS_H_

#include <zephyr/net/buf.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Run reboot RPC
 *
 * @param request @ref INFUSE_RPC_REQ packet to respond to
 *
 * @return struct net_buf* @ref INFUSE_RPC_RSP packet buffer
 */
struct net_buf *rpc_command_reboot(struct net_buf *request);

/**
 * @brief Run fault RPC
 *
 * @param request @ref INFUSE_RPC_REQ packet to respond to
 *
 * @return struct net_buf* @ref INFUSE_RPC_RSP packet buffer
 */
struct net_buf *rpc_command_fault(struct net_buf *request);

/**
 * @brief Run time_get RPC
 *
 * @param request @ref INFUSE_RPC_REQ packet to respond to
 *
 * @return struct net_buf* @ref INFUSE_RPC_RSP packet buffer
 */
struct net_buf *rpc_command_time_get(struct net_buf *request);

/**
 * @brief Run time_set RPC
 *
 * @param request @ref INFUSE_RPC_REQ packet to respond to
 *
 * @return struct net_buf* @ref INFUSE_RPC_RSP packet buffer
 */
struct net_buf *rpc_command_time_set(struct net_buf *request);

/**
 * @brief Run kv_write RPC
 *
 * @param request @ref INFUSE_RPC_REQ packet to respond to
 *
 * @return struct net_buf* @ref INFUSE_RPC_RSP packet buffer
 */
struct net_buf *rpc_command_kv_write(struct net_buf *request);

/**
 * @brief Run kv_read RPC
 *
 * @param request @ref INFUSE_RPC_REQ packet to respond to
 *
 * @return struct net_buf* @ref INFUSE_RPC_RSP packet buffer
 */
struct net_buf *rpc_command_kv_read(struct net_buf *request);

/**
 * @brief Run wifi_scan RPC
 *
 * @param request @ref INFUSE_RPC_REQ packet to respond to
 *
 * @return struct net_buf* @ref INFUSE_RPC_RSP packet buffer
 */
struct net_buf *rpc_command_wifi_scan(struct net_buf *request);

/**
 * @brief Run wifi_state RPC
 *
 * @param request @ref INFUSE_RPC_REQ packet to respond to
 *
 * @return struct net_buf* @ref INFUSE_RPC_RSP packet buffer
 */
struct net_buf *rpc_command_wifi_state(struct net_buf *request);

/**
 * @brief Run security_state RPC
 *
 * @param request @ref INFUSE_RPC_REQ packet to respond to
 *
 * @return struct net_buf* @ref INFUSE_RPC_RSP packet buffer
 */
struct net_buf *rpc_command_security_state(struct net_buf *request);

/**
 * @brief Run data_sender RPC
 *
 * @param request @ref INFUSE_RPC_REQ packet to respond to
 *
 * @return struct net_buf* @ref INFUSE_RPC_RSP packet buffer
 */
struct net_buf *rpc_command_data_sender(struct net_buf *request);

/**
 * @brief Run data_receiver RPC
 *
 * @param request @ref INFUSE_RPC_REQ packet to respond to
 *
 * @return struct net_buf* @ref INFUSE_RPC_RSP packet buffer
 */
struct net_buf *rpc_command_data_receiver(struct net_buf *request);

/**
 * @brief Run echo RPC
 *
 * @param request @ref INFUSE_RPC_REQ packet to respond to
 *
 * @return struct net_buf* @ref INFUSE_RPC_RSP packet buffer
 */
struct net_buf *rpc_command_echo(struct net_buf *request);

#ifdef __cplusplus
}
#endif

#endif /* INFUSE_SDK_SUBSYS_RPC_COMMANDS_COMMANDS_H_ */
