/*
 * Copyright (c) 2015 Wind River Systems, Inc.
 * Copyright (c) 2018 Intel Corporation
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <math.h>

#include <zephyr/ztest.h>

#include <infuse/math/common.h>

ZTEST(infuse_math, test_sqrt16)
{
	/* Exhaustive test over uint16_t */
	for (uint32_t i = 0; i <= UINT16_MAX; i++) {
		uint8_t stdlib_res = (uint8_t)sqrtf((float)i);

		zassert_equal(stdlib_res, math_sqrt16(i));
	}
}

ZTEST(infuse_math, test_sqrt32)
{
	/* Exhaustive test over uint16_t input range */
	for (uint32_t i = 0; i <= UINT16_MAX; i++) {
		uint16_t stdlib_res = (uint16_t)sqrt((double)i);

		zassert_equal(stdlib_res, math_sqrt32(i));
	}

	/* Test each value in the uint16_t output range */
	for (uint32_t i = UINT8_MAX; i <= UINT16_MAX; i++) {
		uint32_t sq = i * i;

		zassert_equal(i, math_sqrt32(sq));
		zassert_equal(i, math_sqrt32(sq + 1));
		zassert_equal(i, math_sqrt32(sq + 2));
	}
}

ZTEST(infuse_math, test_sqrt64)
{
	/* Exhaustive test over uint16_t input range */
	for (uint32_t i = 0; i <= UINT16_MAX; i++) {
		uint32_t stdlib_res = (uint32_t)sqrt((double)i);

		zassert_equal(stdlib_res, math_sqrt64(i));
	}

	/* Test a range of other values */
	uint64_t i = UINT16_MAX;

	while (i < (1llu << 60)) {
		uint32_t stdlib_res = (uint32_t)sqrt((double)i);

		zassert_equal(stdlib_res, math_sqrt64(i));

		/* Jump up by a bit */
		i = (6 * i / 5) + 3333;
	}
}

ZTEST(infuse_math, test_vector_xy_mag)
{
	/* Single element */
	for (int32_t i = INT16_MIN; i <= INT16_MAX; i++) {
		zassert_equal(math_abs(i), math_vector_xy_magnitude(i, 0));
		zassert_equal(math_abs(i), math_vector_xy_magnitude(0, i));
	}

	/* Random points generated by testcase_gen.py */
	zassert_equal(31496, math_vector_xy_magnitude(-28274, -13879));
	zassert_equal(13581, math_vector_xy_magnitude(12259, 5845));
	zassert_equal(30412, math_vector_xy_magnitude(27369, -13260));
	zassert_equal(34052, math_vector_xy_magnitude(11340, -32109));
	zassert_equal(28139, math_vector_xy_magnitude(24663, 13548));
	zassert_equal(20303, math_vector_xy_magnitude(12157, -16261));
	zassert_equal(17803, math_vector_xy_magnitude(-5791, -16835));
	zassert_equal(17975, math_vector_xy_magnitude(17698, 3147));
	zassert_equal(14130, math_vector_xy_magnitude(-6126, 12733));
	zassert_equal(31635, math_vector_xy_magnitude(27178, -16191));
}

ZTEST(infuse_math, test_vector_xyz_mag)
{
	/* Single element */
	for (int32_t i = INT16_MIN; i <= INT16_MAX; i++) {
		zassert_equal(math_abs(i), math_vector_xyz_magnitude(i, 0, 0));
		zassert_equal(math_abs(i), math_vector_xyz_magnitude(0, i, 0));
		zassert_equal(math_abs(i), math_vector_xyz_magnitude(0, 0, i));
	}

	/* Random points generated by testcase_gen.py */
	zassert_equal(28714, math_vector_xyz_magnitude(-28054, -4642, 3993));
	zassert_equal(46747, math_vector_xyz_magnitude(32540, -29457, 16085));
	zassert_equal(37683, math_vector_xyz_magnitude(17323, 31538, 11195));
	zassert_equal(43732, math_vector_xyz_magnitude(24499, -28893, 21852));
	zassert_equal(25019, math_vector_xyz_magnitude(-5454, 13891, 20081));
	zassert_equal(35558, math_vector_xyz_magnitude(1798, 13791, -32726));
	zassert_equal(46459, math_vector_xyz_magnitude(29712, 15964, -31950));
	zassert_equal(13975, math_vector_xyz_magnitude(5101, -9846, 8506));
	zassert_equal(36871, math_vector_xyz_magnitude(16105, 6128, 32597));
	zassert_equal(37947, math_vector_xyz_magnitude(28969, -24428, -2019));
}

ZTEST_SUITE(infuse_math, NULL, NULL, NULL, NULL, NULL);
