/*
 * Copyright (c) 2024 Embeint Holdings Pty Ltd
 *
 * SPDX-License-Identifier: FSL-1.1-ALv2
 */

#include <math.h>

#include <zephyr/ztest.h>

#include <infuse/math/common.h>

ZTEST(infuse_math, test_sqrt16)
{
	/* Exhaustive test over uint16_t */
	for (uint32_t i = 0; i <= UINT16_MAX; i++) {
		uint8_t stdlib_res = (uint8_t)sqrtf((float)i);

		zassert_equal(stdlib_res, math_sqrt16(i));
	}
}

ZTEST(infuse_math, test_sqrt32)
{
	/* Exhaustive test over uint16_t input range */
	for (uint32_t i = 0; i <= UINT16_MAX; i++) {
		uint16_t stdlib_res = (uint16_t)sqrt((double)i);

		zassert_equal(stdlib_res, math_sqrt32(i));
	}

	/* Test each value in the uint16_t output range */
	for (uint32_t i = UINT8_MAX; i <= UINT16_MAX; i++) {
		uint32_t sq = i * i;

		zassert_equal(i, math_sqrt32(sq));
		zassert_equal(i, math_sqrt32(sq + 1));
		zassert_equal(i, math_sqrt32(sq + 2));
	}
}

ZTEST(infuse_math, test_inv_sqrt32)
{
	/* Test a good chunk of values */
	for (float i = 1.0f; i < 1000000.0f; i += 0.25f) {
		float stdlib_res = 1 / sqrtf(i);

		zassert_within(stdlib_res, math_inverse_sqrt32(i), 0.001f);
	}
}

ZTEST(infuse_math, test_sqrt64)
{
	/* Exhaustive test over uint16_t input range */
	for (uint32_t i = 0; i <= UINT16_MAX; i++) {
		uint32_t stdlib_res = (uint32_t)sqrt((double)i);

		zassert_equal(stdlib_res, math_sqrt64(i));
	}

	/* Test a range of other values */
	uint64_t i = UINT16_MAX;

	while (i < (1llu << 60)) {
		uint32_t stdlib_res = (uint32_t)sqrt((double)i);

		zassert_equal(stdlib_res, math_sqrt64(i));

		/* Jump up by a bit */
		i = (6 * i / 5) + 3333;
	}
}

ZTEST(infuse_math, test_vector_xy_mag)
{
	/* Single element */
	for (int32_t i = INT16_MIN; i <= INT16_MAX; i++) {
		zassert_equal(math_abs(i), math_vector_xy_magnitude(i, 0));
		zassert_equal(math_abs(i), math_vector_xy_magnitude(0, i));
	}

	/* Random points generated by testcase_gen.py */
	zassert_equal(31496, math_vector_xy_magnitude(-28274, -13879));
	zassert_equal(13581, math_vector_xy_magnitude(12259, 5845));
	zassert_equal(30412, math_vector_xy_magnitude(27369, -13260));
	zassert_equal(34052, math_vector_xy_magnitude(11340, -32109));
	zassert_equal(28139, math_vector_xy_magnitude(24663, 13548));
	zassert_equal(20303, math_vector_xy_magnitude(12157, -16261));
	zassert_equal(17803, math_vector_xy_magnitude(-5791, -16835));
	zassert_equal(17975, math_vector_xy_magnitude(17698, 3147));
	zassert_equal(14130, math_vector_xy_magnitude(-6126, 12733));
	zassert_equal(31635, math_vector_xy_magnitude(27178, -16191));
}

ZTEST(infuse_math, test_vector_xyz_mag)
{
	/* Single element */
	for (int32_t i = INT16_MIN; i <= INT16_MAX; i++) {
		zassert_equal(math_abs(i), math_vector_xyz_magnitude(i, 0, 0));
		zassert_equal(math_abs(i), math_vector_xyz_magnitude(0, i, 0));
		zassert_equal(math_abs(i), math_vector_xyz_magnitude(0, 0, i));
	}

	/* Random points generated by testcase_gen.py */
	zassert_equal(28714, math_vector_xyz_magnitude(-28054, -4642, 3993));
	zassert_equal(46747, math_vector_xyz_magnitude(32540, -29457, 16085));
	zassert_equal(37683, math_vector_xyz_magnitude(17323, 31538, 11195));
	zassert_equal(43732, math_vector_xyz_magnitude(24499, -28893, 21852));
	zassert_equal(25019, math_vector_xyz_magnitude(-5454, 13891, 20081));
	zassert_equal(35558, math_vector_xyz_magnitude(1798, 13791, -32726));
	zassert_equal(46459, math_vector_xyz_magnitude(29712, 15964, -31950));
	zassert_equal(13975, math_vector_xyz_magnitude(5101, -9846, 8506));
	zassert_equal(36871, math_vector_xyz_magnitude(16105, 6128, 32597));
	zassert_equal(37947, math_vector_xyz_magnitude(28969, -24428, -2019));
}

ZTEST(infuse_math, test_vector_xyz_dot_product)
{
	zassert_equal(1, math_vector_xyz_dot_product(1, 0, 0, 1, 0, 0));
	zassert_equal(1, math_vector_xyz_dot_product(0, 1, 0, 0, 1, 0));
	zassert_equal(1, math_vector_xyz_dot_product(0, 0, 1, 0, 0, 1));
	zassert_equal(3, math_vector_xyz_dot_product(1, 1, 1, 1, 1, 1));
	zassert_equal(-3, math_vector_xyz_dot_product(-1, -1, -1, 1, 1, 1));
	zassert_equal(3, math_vector_xyz_dot_product(1, 3, -5, 4, -2, -1));
	zassert_equal(35, math_vector_xyz_dot_product(1, 3, -5, 1, 3, -5));
	zassert_equal(-33000000, math_vector_xyz_dot_product(1000, 3000, -5000, 1000, -3000, 5000));

	zassert_equal(3221225472, math_vector_xyz_dot_product(INT16_MIN, INT16_MIN, INT16_MIN,
							      INT16_MIN, INT16_MIN, INT16_MIN));
	zassert_equal(-3221127168, math_vector_xyz_dot_product(INT16_MIN, INT16_MIN, INT16_MIN,
							       INT16_MAX, INT16_MAX, INT16_MAX));
	zassert_equal(3221028867, math_vector_xyz_dot_product(INT16_MAX, INT16_MAX, INT16_MAX,
							      INT16_MAX, INT16_MAX, INT16_MAX));
}

ZTEST(infuse_math, test_vector_xyz_dot_product_fast)
{
	zassert_equal(1, math_vector_xyz_dot_product_fast(1, 0, 0, 1, 0, 0));
	zassert_equal(1, math_vector_xyz_dot_product_fast(0, 1, 0, 0, 1, 0));
	zassert_equal(1, math_vector_xyz_dot_product_fast(0, 0, 1, 0, 0, 1));
	zassert_equal(3, math_vector_xyz_dot_product_fast(1, 1, 1, 1, 1, 1));
	zassert_equal(-3, math_vector_xyz_dot_product_fast(-1, -1, -1, 1, 1, 1));
	zassert_equal(3, math_vector_xyz_dot_product_fast(1, 3, -5, 4, -2, -1));
	zassert_equal(35, math_vector_xyz_dot_product_fast(1, 3, -5, 1, 3, -5));
	zassert_equal(-33000000,
		      math_vector_xyz_dot_product_fast(1000, 3000, -5000, 1000, -3000, 5000));

	/* Overflow gives incorrect answer */
	zassert_true(3221028867 > math_vector_xyz_dot_product_fast(INT16_MAX, INT16_MAX, INT16_MAX,
								   INT16_MAX, INT16_MAX,
								   INT16_MAX));
}

ZTEST(infuse_math, test_bitmask_get_next)
{
	uint8_t next_idx;

	/* Request more bits than exist*/
	next_idx = 0;
	zassert_equal(0x0FF0, math_bitmask_get_next_bits(0x0FF0, next_idx, &next_idx, 12));
	zassert_equal(0x0FF0, math_bitmask_get_next_bits(0x0FF0, next_idx, &next_idx, 12));
	zassert_equal(0x0FF0, math_bitmask_get_next_bits(0x0FF0, next_idx, &next_idx, 12));

	/* Request no bits */
	next_idx = 0;
	zassert_equal(0x0000, math_bitmask_get_next_bits(0x0FF0, next_idx, &next_idx, 0));
	zassert_equal(0x0000, math_bitmask_get_next_bits(0x0FF0, next_idx, &next_idx, 0));
	zassert_equal(0x0000, math_bitmask_get_next_bits(0x0FF0, next_idx, &next_idx, 0));

	/* Basic iteration */
	next_idx = 0;
	zassert_equal(0x000F, math_bitmask_get_next_bits(0xFFFF, next_idx, &next_idx, 4));
	zassert_equal(0x00F0, math_bitmask_get_next_bits(0xFFFF, next_idx, &next_idx, 4));
	zassert_equal(0x0F00, math_bitmask_get_next_bits(0xFFFF, next_idx, &next_idx, 4));
	zassert_equal(0xF000, math_bitmask_get_next_bits(0xFFFF, next_idx, &next_idx, 4));
	zassert_equal(0x000F, math_bitmask_get_next_bits(0xFFFF, next_idx, &next_idx, 4));

	/* Missing bits */
	next_idx = 0;
	zassert_equal(0x000A, math_bitmask_get_next_bits(0xAAAA, next_idx, &next_idx, 2));
	zassert_equal(0x00A0, math_bitmask_get_next_bits(0xAAAA, next_idx, &next_idx, 2));
	zassert_equal(0x0A00, math_bitmask_get_next_bits(0xAAAA, next_idx, &next_idx, 2));
	zassert_equal(0xA000, math_bitmask_get_next_bits(0xAAAA, next_idx, &next_idx, 2));
	zassert_equal(0x000A, math_bitmask_get_next_bits(0xAAAA, next_idx, &next_idx, 2));

	/* Odd pattern and iteration */
	next_idx = 0;
	zassert_equal(0x00000002, math_bitmask_get_next_bits(0x7000438A, next_idx, &next_idx, 1));
	zassert_equal(0x00000008, math_bitmask_get_next_bits(0x7000438A, next_idx, &next_idx, 1));
	zassert_equal(0x00000080, math_bitmask_get_next_bits(0x7000438A, next_idx, &next_idx, 1));
	zassert_equal(0x00000300, math_bitmask_get_next_bits(0x7000438A, next_idx, &next_idx, 2));
	zassert_equal(0x10004000, math_bitmask_get_next_bits(0x7000438A, next_idx, &next_idx, 2));
	zassert_equal(0x60000002, math_bitmask_get_next_bits(0x7000438A, next_idx, &next_idx, 3));
	zassert_equal(0x00000008, math_bitmask_get_next_bits(0x7000438A, next_idx, &next_idx, 1));
}

ZTEST(infuse_math, test_2d_linear_interpolate)
{
	zassert_equal(0, math_2d_linear_interpolate_fast(-5, 5, -5, 5, 0));
	zassert_equal(-5, math_2d_linear_interpolate_fast(-5, 5, -5, 5, -5));
	zassert_equal(5, math_2d_linear_interpolate_fast(-5, 5, -5, 5, 5));
	zassert_equal(5, math_2d_linear_interpolate_fast(-5, 5, 5, -5, -5));
	zassert_equal(-5, math_2d_linear_interpolate_fast(-5, 5, 5, -5, 5));

	for (int i = 0; i <= 100; i++) {
		zassert_equal(i, math_2d_linear_interpolate_fast(0, 100, 0, 100, i));
		zassert_equal(2 * i, math_2d_linear_interpolate_fast(0, 100, 0, 200, i));
		zassert_equal(-5 * i, math_2d_linear_interpolate_fast(0, 100, 0, -500, i));
	}

	int32_t lim_min = -23170;
	int32_t lim_max = 23170;

	/* At guaranteed limits */
	zassert_equal(0, math_2d_linear_interpolate_fast(lim_min, lim_max, lim_min, lim_max, 0));
	zassert_equal(lim_min,
		      math_2d_linear_interpolate_fast(lim_min, lim_max, lim_min, lim_max, lim_min));
	zassert_equal(lim_max,
		      math_2d_linear_interpolate_fast(lim_min, lim_max, lim_min, lim_max, lim_max));
	zassert_equal(lim_max,
		      math_2d_linear_interpolate_fast(lim_min, lim_max, lim_max, lim_min, lim_min));
	zassert_equal(lim_min,
		      math_2d_linear_interpolate_fast(lim_min, lim_max, lim_max, lim_min, lim_max));
}

ZTEST_SUITE(infuse_math, NULL, NULL, NULL, NULL, NULL);
